define({
  "viz_settings": "Vizualizacijos parametrai",
  "viz_type": "Vizualizacijos tipas",
  "max_height": "Maksimalus simbolio aukštis (metrais)",
  "max_width": "Maksimalus simbolio plotis (metrais)",
  "interval": "Intervalas (milisekundėmis)",
  "show_percent": "Visas reikšmes rodyti procentine išraiška",
  "show_jettrail_end_points": "Rodyti pabaigos taškus",
  "show_percentage_limited": "Išjungta, nes įrašų skaičius didesnis nei 400.",
  "cycle_colors": "Automatiškai keisti spalvas",
  "area_extrusion": "Ploto poslinkis",
  "bounce": "Bounce",
  "fireball": "Fireball",
  "grid_surface": " Tinklelio paviršius",
  "jet_trail": "Lėktuvo takas",
  "point_extrusion": "Taško poslinkis",
  "pulse": "Pulse",
  "layer_settings": "Sluoksnio parametrai",
  "viz_layer": "Vizualizacijos sluoksnis",
  "display_field": "Rodyti lauką",
  "add_field": "Įtraukti vizualizacijos lauką",
  "field": "Laukas",
  "label": "Žymė",
  "actions": "Veiksmai",
  "no_layers": " Pasirinktoje internetinėje scenoje nėra galimų sluoksnių",
  "viz_not_supported": "Nepalaikoma dėl pasirinkto sluoksnio geometrijos tipo."
});