define({
  "viz_settings": "Megjelenítési beállítások",
  "viz_type": "Megjelenítés típusa",
  "max_height": "Max. szimbólummagasság (méter)",
  "max_width": "Max. szimbólumszélesség (méter)",
  "interval": "Időköz (ezredmásodperc)",
  "show_percent": "Értékek mutatása az összes érték százalékában kifejezve",
  "show_jettrail_end_points": "Végpontok megjelenítése",
  "show_percentage_limited": "Ez a beállítás le van tiltva, mivel a rekordok száma meghaladja a 400-at.",
  "cycle_colors": "Színek automatikus módosítása",
  "area_extrusion": "Terület térbeliesítés",
  "bounce": "Pattogás",
  "fireball": "Tűzgömb",
  "grid_surface": " Rácsfelület",
  "jet_trail": "Kondenzcsík",
  "point_extrusion": "Pont térbeliesítés",
  "pulse": "Pulzálás",
  "layer_settings": "Rétegbeállítások",
  "viz_layer": "Megjelenítési réteg",
  "display_field": "Megjelenítési mező",
  "add_field": "Megjelenítési mező hozzáadása",
  "field": "Mező",
  "label": "Felirat",
  "actions": "Műveletek",
  "no_layers": " Nincsenek elérhető rétegek a kiválasztott web 3D térképen.",
  "viz_not_supported": "Nem támogatott a kiválasztott réteg geometria-típusához."
});