// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:builder/plugins/attribute-config/AttrbuteLogoChooser.html":'\x3cdiv class\x3d"jimu-float-leading jimu-trailing-margin1" data-dojo-attach-point\x3d"logoContainer"\r\n data-dojo-attach-event\x3d"onmouseenter:onMouseEnterHandler"\r\n data-dojo-attach-event\x3d"onmouseleave:onMouseLeaveHandler"\x3e\r\n  \x3cdiv data-dojo-type\x3d"jimu/dijit/ImageChooser" data-dojo-attach-point\x3d"imageChooser"\r\n  data-dojo-props\x3d"cropImage:false,showSelfImg:true,stretchImg:false,goldenWidth:30,goldenHeight:30,format:[\'image/gif\',\'image/png\',\'image/jpeg\']"\x3e\x3c/div\x3e\r\n  \x3cdiv class\x3d"add-logo" data-dojo-attach-point\x3d"addLogoNode"\x3e\r\n    \x3cdiv class\x3d"image"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\r\n  \x3cdiv class\x3d"masker-node" data-dojo-attach-point\x3d"maskerNode"\x3e\x3c/div\x3e\r\n\r\n  \x3cdiv class\x3d"remove-logo" data-dojo-attach-point\x3d"removeLogoNode" data-dojo-attach-event\x3d"onclick:onRemoveLogoHandler"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/Evented dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/_base/lang dojo/_base/html dojo/on dojo/text!./AttrbuteLogoChooser.html jimu/dijit/Popup builder/dijit/SharedThemeChooserPopup ./CustomLogoPage dojo/sniff jimu/dijit/ImageChooser".split(" "),function(g,h,k,l,m,d,b,e,n,p,q,r,f){return h([k,l,m,g],{baseClass:"logo-container no-logo",declaredClass:"jimu.dijit.AttrbuteLogoChooser",templateString:n,isPortalSupport:!1,_wabDefaultLogo:!0,postCreate:function(){this.inherited(arguments);
b.setAttr(this.removeLogoNode,"title",this.nls.removeLogo)},startup:function(){this._createTooltipDialog();this.own(e(this.imageChooser,"imageChange",d.hitch(this,"_onLogoChoosed")));this.own(e(this.maskerNode,"mouseenter",d.hitch(this,function(){this.popup.showPopup()})));this.own(e(this.maskerNode,"mouseleave",d.hitch(this,function(){this.popup.hidePopup()})))},setLogo:function(a){this._wabDefaultLogo="images/app-logo.png"===a?!0:!1;a?(!a||a.startWith("/")||a.startWith("http")||a.startWith("data")||
(a=window.appInfo.appPath+a),this.imageChooser.setDefaultSelfSrc(a),b.addClass(this.logoContainer,"logo"),b.removeClass(this.logoContainer,"no-logo"),b.addClass(this.addLogoNode,"hide"),this._resetLogoBox(50)):(this.imageChooser.setDefaultSelfSrc(a),b.addClass(this.logoContainer,"no-logo"))},setLink:function(a){this.link=a},setSharedThemeConfig:function(a){a&&"undefined"!==typeof a.useLogo&&(this._useLogo=a.useLogo,this.popup.setIsPortalSupport(a.isPortalSupport),this._isNoChooseState()||(!0===a.useLogo?
this.showSharedThemeLogo(!1):this.setCustomLogo(!1)))},_isNoChooseState:function(){return!1===this._useLogo&&!0===this._wabDefaultLogo?!0:!1},onRemoveLogoHandler:function(a){a.stopPropagation();a.preventDefault();this.imageChooser.imageData&&(this.imageChooser.setDefaultSelfSrc(""),b.removeClass(this.logoContainer,"logo"),b.removeClass(this.addLogoNode,"hide"),b.addClass(this.logoContainer,"no-logo"),this.setCustomLogo(),this.emit("appAttributeChanged",{logo:""}))},onChangeLogoHandler:function(a){a.stopPropagation();
a.preventDefault();this.popup.showTooltipDialog()},setDiskLogo:function(){var a=this.imageChooser.mask;if(f("safari")){var b=document.createEvent("MouseEvents");b.initEvent("click",!0,!0);a.dispatchEvent(b)}else a.click();this.popup.hideTooltipDialog()},_onLogoChoosed:function(a){this._changeLogo();this.emit("appAttributeChanged",{logo:a});this.setCustomLogo()},_onLinkChange:function(a){this.emit("appAttributeChanged",{logoLink:a});this.setCustomLogo()},showSharedThemeLogo:function(a){this.popup.setChecked(this.popup.ACTION.SHARED);
this.emitSharedThemeChangedEvent(!0,a)},showCustomLogo:function(){this.popup.setChecked(this.popup.ACTION.CUSTOM)},setCustomLogo:function(a){this.emitSharedThemeChangedEvent(!1,a)},emitSharedThemeChangedEvent:function(a,b){!1!==b&&this.emit("sharedThemeChanged",{useLogo:a});this.popup.hideTooltipDialog()},_changeLogo:function(){b.setStyle(this.imageChooser.selfImg,{width:"auto",height:"auto",marginLeft:"auto",marginRight:"auto",marginTop:"auto",marginBottom:"auto"});b.removeClass(this.logoContainer,
"no-logo");b.addClass(this.logoContainer,"logo");b.addClass(this.addLogoNode,"hide");b.removeClass(this.imageChooser.domNode,"hide");setTimeout(d.hitch(this,this._resetLogoBox,4),4)},_resetLogoBox:function(a){if(this.domNode&&this.imageChooser){var c=b.getContentBox(this.imageChooser.selfImg);0<c.w?(a=b.getContentBox(this.imageChooser.domNode),c=c.w/c.h,1>=c?(b.setStyle(this.imageChooser.selfImg,"height",a.h+"px"),c=(a.w-a.h*c)/2,b.setStyle(this.imageChooser.selfImg,{marginLeft:c+"px",marginRight:c+
"px"})):(b.setStyle(this.imageChooser.selfImg,"width",a.w+"px"),c=(a.h-a.w/c)/2,b.setStyle(this.imageChooser.selfImg,{marginTop:c+"px",marginBottom:c+"px"}))):setTimeout(d.hitch(this,this._resetLogoBox,a),a)}},onMouseEnterHandler:function(){10>f("ie")&&(this._hasEntered?b.setStyle(this.removeLogoNode,{display:"block"}):setTimeout(d.hitch(this,function(){var a=b.position(this.logoContainer);b.place(this.removeLogoNode,this.ownerDocumentBody);b.addClass(this.removeLogoNode,"attribute-config-plugin-logo-options");
b.setStyle(this.removeLogoNode,{position:"absolute",display:"block",left:(window.isRTL?a.x+5:a.x+a.w-35)+"px",top:a.y+5+"px"});this._hasEntered=!0})))},onMouseLeaveHandler:function(){10>f("ie")&&(b.setStyle(this.removeLogoNode,{display:"none"}),this._hasEntered=!1)},destroy:function(){this.popup.destroy();this.inherited(arguments)},_createTooltipDialog:function(){this.popup=new q({isPortalSupport:this.isPortalSupport,placeAt:this.getParent(),around:this.domNode});this.own(e(this.popup,"btnClick",
d.hitch(this,function(a){a===this.popup.ACTION.SHARED?this.showSharedThemeLogo():a===this.popup.ACTION.CUSTOM&&this.showCustomPopup()})));this.own(e(this.popup,"showPopup",d.hitch(this,function(){this._isNoChooseState()||this.popup.setChecked(this._useLogo?this.popup.ACTION.SHARED:this.popup.ACTION.CUSTOM)})))},showCustomPopup:function(){this.popup.hideTooltipDialog();this.customLogoPage=new r({nls:this.nls,link:this.link,imageChooser:this.imageChooser});this.customPopup=new p({content:this.customLogoPage,
titleLabel:this.nls.setLogo,width:669,autoHeight:!0,buttons:[{label:this.nls.ok,onClick:d.hitch(this,function(){if(this.customLogoPage.isValid()){var a=this.customLogoPage.getLink();this.setLink(a);this._onLinkChange(a);this.customPopup.close()}})},{label:this.nls.cancel,onClick:d.hitch(this,function(){this.customPopup.close()})}]})}})});