define({
  "viz_settings": "Configuració de visualització",
  "viz_type": "Tipus de visualització",
  "max_height": "Altura màxima del símbol (metres)",
  "max_width": "Amplada màxima del símbol (metres)",
  "interval": "Interval (mil·lisegons)",
  "show_percent": "Mostra els valors com a percentatges de tots els valors",
  "show_jettrail_end_points": "Mostra els extrems",
  "show_percentage_limited": "S'ha deshabilitat perquè el nombre de registres és superior a 400.",
  "cycle_colors": "Canvia els colors automàticament",
  "area_extrusion": "Extrusió d'àrea",
  "bounce": "Rebot",
  "fireball": "Bola de foc",
  "grid_surface": " Superfície de quadrícula",
  "jet_trail": "Deixant de reactor",
  "point_extrusion": "Extrusió de punt",
  "pulse": "Pols",
  "layer_settings": "Configuració de capa",
  "viz_layer": "Capa de visualització",
  "display_field": "Mostra el camp",
  "add_field": "Afegeix un camp de visualització",
  "field": "Camp",
  "label": "Etiqueta",
  "actions": "Accions",
  "no_layers": " No hi ha cap capa disponible a l'escena web seleccionada.",
  "viz_not_supported": "No és compatible amb el tipus de geometria de la capa seleccionada."
});