define({
  "viz_settings": "Visualisierungseinstellungen",
  "viz_type": "Visualisierungstyp",
  "max_height": "Maximale Symbolhöhe (Meter)",
  "max_width": "Maximale Symbolbreite (Meter)",
  "interval": "Intervall (Millisekunden)",
  "show_percent": "Werte als Prozentsatz aller Werte anzeigen",
  "show_jettrail_end_points": "Endpunkte anzeigen",
  "show_percentage_limited": "Diese Option ist deaktiviert, da die Anzahl der Datensätze mehr als 400 beträgt.",
  "cycle_colors": "Farben automatisch ändern",
  "area_extrusion": "Flächenextrusion",
  "bounce": "Springen",
  "fireball": "Feuerball",
  "grid_surface": " Gitternetzoberfläche",
  "jet_trail": "Kondensstreifen",
  "point_extrusion": "Punktextrusion",
  "pulse": "Impuls",
  "layer_settings": "Layer-Einstellungen",
  "viz_layer": "Visualisierungs-Layer",
  "display_field": "Feld anzeigen",
  "add_field": "Visualisierungsfeld hinzufügen",
  "field": "Feld",
  "label": "Beschriftung",
  "actions": "Aktionen",
  "no_layers": " In der ausgewählten Webszene sind keine Layer verfügbar.",
  "viz_not_supported": "Wird für den Geometrietyp des ausgewählten Layers nicht unterstützt."
});