define({
  "viz_settings": "दृश्य सेटिंग",
  "viz_type": "दृश्य का प्रकार",
  "max_height": "अधिकतम प्रतीक ऊंचाई (मीटर)",
  "max_width": "अधिकतम प्रतीक चौड़ाई (मीटर)",
  "interval": "अंतराल (मिलीसेकेंड)",
  "show_percent": "सभी मानों के प्रतिशत के रूप में मान दिखाएं",
  "show_jettrail_end_points": "समाप्ति बिंदु दिखाएँ",
  "show_percentage_limited": "यह अक्षम है क्योंकि रिकॉर्ड की संख्या 400 से भी अधिक है।",
  "cycle_colors": "स्वचालित रूप से रंग बदलता है",
  "area_extrusion": "क्षेत्र बाहर निकालना",
  "bounce": "उछाल",
  "fireball": "फायरबॉल",
  "grid_surface": " ग्रिड सतह",
  "jet_trail": "जेट ट्रेल",
  "point_extrusion": "बिंदु बाहर निकालना",
  "pulse": "पल्स",
  "layer_settings": "लेयर सेटिंग",
  "viz_layer": "दृश्य लेयर",
  "display_field": "डिस्प्ले फील्ड्स",
  "add_field": "दृश्य फ़ील्ड जोड़ें",
  "field": "फ़ील्ड",
  "label": "लेबल",
  "actions": "कार्रवाइयाँ",
  "no_layers": " चयनित वेब दृश्य में कोई लेयर उपलब्ध नहीं है।",
  "viz_not_supported": "चयनित लेयर की Geometry प्रकार का समर्थन नहीं करता है।"
});