define({
  "viz_settings": "Visualiseringsindstillinger",
  "viz_type": "Visualiseringstype",
  "max_height": "Maks. symbolhøjde (meter)",
  "max_width": "Maks. symbolbredde (meter)",
  "interval": "Interval (millisekunder)",
  "show_percent": "Vis værdier som en procent af alle værdier",
  "show_jettrail_end_points": "Vis slutpunkter",
  "show_percentage_limited": "Dette er deaktiveret, fordi antallet af poster er større end 400.",
  "cycle_colors": "Skift farver automatisk",
  "area_extrusion": "Områdeudtrækning",
  "bounce": "Bounce",
  "fireball": "Fireball",
  "grid_surface": " Gitteroverflade",
  "jet_trail": "Flyspor",
  "point_extrusion": "Punktudtrækning",
  "pulse": "Puls",
  "layer_settings": "Lagindstillinger",
  "viz_layer": "Visualiseringslag",
  "display_field": "Visningsfelt",
  "add_field": "Tilføj visualiseringsfelt",
  "field": "Mark",
  "label": "Mærke",
  "actions": "Handlinger",
  "no_layers": " Ingen lag er tilgængelige i den valgte webscene.",
  "viz_not_supported": "Understøttes ikke for geometritypen for det valgte lag."
});