// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:builder/plugins/app-list/AppCardPage.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"app-card-page-content" id\x3d"app-card-page-content" data-dojo-attach-point\x3d"appCardPageContent"\x3e\x3c/div\x3e\r\n\x3c/div\x3e\r\n\r\n'}});
define("dojo/_base/declare dojo/_base/html dojo/_base/array dojo/_base/lang dojo/_base/fx dojo/on dojo/dom ./AppOperMenu dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./AppCardPage.html dojox/form/Uploader dojo/NodeList-dom".split(" "),function(r,a,n,p,g,h,t,u,v,w,x,y){return r([v,w,x],{baseClass:"app-card-page",templateString:y,loading:null,folderUrl:null,appListWidget:null,_eventHandles:null,_appOperMenus:null,postMixInProperties:function(){this.inherited(arguments);
this.nls=this.appListWidget.nls;this.loading=this.appListWidget.loading;this.folderUrl=this.appListWidget.folderUrl},constructor:function(){this._eventHandles=[];this._appOperMenus=[]},startup:function(){this.inherited(arguments);a.setSelectable(this.domNode,!1)},refresh:function(a){this.createAppList(a)},cleanAppList:function(){a.empty(this.appCardPageContent);n.forEach(this._appOperMenus,function(a){a.destroy()});this._appOperMenus=[];n.forEach(this._eventHandles,function(a){a.remove()});this._eventHandles=
[]},createAppList:function(a){this.cleanAppList();n.forEach(a,function(a){this.createAppCard(a)},this)},createAppCard:function(c){var q=a.create("div",{"class":"app-card-box jimu-float-leading"},this.appCardPageContent),l=a.create("div",{"class":"card app-info-card"},q);a.create("div",{"class":"app-style-part",style:"background-color: "+c.styleColor},l);var k=a.create("div",{"class":"app-title-part"},l);a.create("div",{"class":"app-type-div "+("HTML"===c.appType?"app-type-2d":"app-type-3d")},k);var b=
a.create("table",{"class":"app-title-table"},k),b=a.create("tbody",{"class":"app-title-table-body"},b),b=a.create("tr",{"class":"app-title-table-tr"},b),d=a.create("td",{"class":"app-icon-td"},b);a.create("div",{"class":"app-icon "+(c._defaultIconClass?c._defaultIconClass:""),style:"background-image: url("+c.icon+"?date\x3d"+this.appListWidget.getRefreshImageFlag()+")"},d);b=a.create("td",{"class":"app-title-td"},b);a.create("div",{"class":"app-title-div",innerHTML:c.name},b);a.create("div",{"class":"app-time-div",
innerHTML:this.appListWidget._getLocaleDateTime(c.lastUpdated)},b);b=a.create("div",{"class":"app-operation-part"},l);a.create("div",{innerHTML:'\x3ca href\x3d"'+c.appUrl+'" target\x3d"_blank"\x3e\x3c/a\x3e',"class":"app-operation launch-operation jimu-float-leading",title:this.nls.launch},b);a.create("div",{innerHTML:'\x3ca href\x3d"'+c.downloadUrl+'" target\x3d"downloadTargetFrame"\x3e\x3c/a\x3e',"class":"app-operation download-operation jimu-float-leading",title:this.nls.download},b);var l=a.create("div",
{"class":"app-operation edit-operation jimu-float-leading",title:this.nls.edit},b),m=a.create("div",{"class":"app-operation more-operation jimu-float-trailing"},b),f=a.create("div",{"class":"app-des-card"},q),b=a.create("div",{"class":"app-des-part"},f),d=a.create("table",{"class":"app-name"},b),d=a.create("tbody",{"class":"app-name-tbody"},d),d=a.create("tr",{"class":"app-name-tr"},d),d=a.create("td",{"class":"app-name-td"},d);a.create("div",{"class":"app-name-div",innerHTML:c.name,title:c.name},
d);d=a.create("div",{"class":"app-info-div"},d);a.create("div",{"class":"app-time-div jimu-float-leading",innerHTML:this.appListWidget._getLocaleDateTime(c.lastUpdated)},d);a.create("div",{"class":"app-creator-div jimu-float-trailing",innerHTML:c.creator},d);a.create("div",{"class":"app-des",innerHTML:c.description,title:c.description},b);var e=(new u({app:c,posNode:m,appListWidget:this.appListWidget,nls:this.nls,isTemplate:c.isTemplate,appContentNode:this.appCardPageContent,height:122,offset:{top:44,
left:-10,right:-10}})).placeAt(m);this._appOperMenus.push(e);e.appTitlePart=k;e.appDesCard=f;b=h(m,"click",p.hitch(this,function(b){e.isShow?(e.hide(),a.removeClass(m,"item-more-selected")):(n.forEach(this._appOperMenus,function(b){b.isShow&&(b.hide(),a.removeClass(b.posNode,"item-more-selected"))}),e.show(),a.addClass(m,"item-more-selected"));b.stopPropagation()}));this._eventHandles.push(b);b=h(l,"click",p.hitch(this,function(){this.appListWidget.pluginManager.getPluginByName("startup").switchToAppConfig(c)}));
this._eventHandles.push(b);b=h(f,"mousemove",function(){g.fadeOut({node:k,duration:150}).play();g.fadeIn({node:f,duration:150}).play()});this._eventHandles.push(b);b=h(f,"mouseout",function(){g.fadeIn({node:k,duration:150}).play();g.fadeOut({node:f,duration:150}).play()});this._eventHandles.push(b);b=h(t.byId("content-box"),"click",p.hitch(this,function(){g.fadeIn({node:k,duration:150}).play();g.fadeOut({node:f,duration:150}).play();a.removeClass(e.posNode,"item-more-selected");e.hide()}));this._eventHandles.push(b);
b=h(q,"click",p.hitch(this,function(a){a.stopPropagation()}));this._eventHandles.push(b)}})});