// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:builder/plugins/app-list/TemplatePage.html":'\x3cdiv\x3e\r\n\t\x3cdiv class\x3d"template-card-page-content" data-dojo-attach-point\x3d"templateCardPageContent"\x3e\x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("dojo/_base/declare dojo/_base/html dojo/_base/array dojo/_base/lang dojo/on dojo/dom ./AppOperMenu dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./TemplatePage.html dojox/form/Uploader dojo/NodeList-dom".split(" "),function(m,a,g,h,k,n,p,q,r,t,u){return m([q,r,t],{baseClass:"template-card-page",templateString:u,loading:null,folderUrl:null,appListWidget:null,_eventHandles:null,_appOperMenus:null,postMixInProperties:function(){this.inherited(arguments);this.nls=
this.appListWidget.nls;this.loading=this.appListWidget.loading;this.folderUrl=this.appListWidget.folderUrl},constructor:function(){this._eventHandles=[];this._appOperMenus=[]},startup:function(){this.inherited(arguments);a.setSelectable(this.domNode,!1)},refresh:function(a){this.createTemplateList(a)},cleanTemplateList:function(){a.empty(this.templateCardPageContent);g.forEach(this._appOperMenus,function(a){a.destroy()});this._appOperMenus=[];g.forEach(this._eventHandles,function(a){a.remove()});
this._eventHandles=[]},createTemplateList:function(a){this.cleanTemplateList();g.forEach(a,function(a){this.createTemplateCard(a)},this)},createTemplateCard:function(c){var d=a.create("div",{"class":"template-card jimu-float-leading"},this.templateCardPageContent);a.create("div",{"class":"template-type-div "+("HTML"===c.appType?"template-type-2d":"template-type-3d")},d);a.create("div",{"class":"thumbnail-part",style:"background-image: url("+c.thumbnail+"?date\x3d"+(new Date).getTime()+")"},d);var l=
a.create("div",{"class":"appInfo-part"},d),b=a.create("table",{"class":"template-name"},l),b=a.create("tbody",{"class":"template-name-tbody"},b),b=a.create("tr",{"class":"template-name-tr"},b),b=a.create("td",{"class":"template-name-td"},b);a.create("div",{"class":"template-name-div",innerHTML:c.name,title:c.name},b);a.create("div",{"class":"template-des-div",innerHTML:c.description,title:c.description},l);d=a.create("div",{"class":"template-operation-part"},d);a.create("div",{innerHTML:'\x3ca href\x3d"'+
c.appUrl+'" target\x3d"_blank"\x3e\x3c/a\x3e',"class":"template-operation launch-operation jimu-float-leading",title:this.nls.preview},d);var l=a.create("div",{"class":"template-operation edit-operation jimu-float-leading "+(c.isPredefined?"disable":""),title:this.nls.edit},d),e=a.create("div",{"class":"template-operation more-operation jimu-float-trailing "+(c.isPredefined?"disable":"")},d),f=(new p({app:c,posNode:e,appListWidget:this.appListWidget,nls:this.nls,isTemplate:c.isTemplate,appContentNode:this.templateCardPageContent,
height:c.isPredefined?45:162,offset:{top:44,left:-10,right:-10}})).placeAt(e);this._appOperMenus.push(f);b=k(e,"click",h.hitch(this,function(b){f.isShow?(f.hide(),a.removeClass(e,"item-more-selected")):(g.forEach(this._appOperMenus,function(b){b.hide();a.removeClass(b.posNode,"item-more-selected")}),f.show(),a.addClass(e,"item-more-selected"));b.stopPropagation()}));this._eventHandles.push(b);b=k(l,"click",h.hitch(this,function(){this.appListWidget.pluginManager.getPluginByName("startup").switchToAppConfig(c)}));
this._eventHandles.push(b);d=a.create("div",{"class":"template-operation create-app-from-template-operation jimu-float-leading",title:this.nls.createApp},d);b=k(d,"click",h.hitch(this,function(){f._onCreateAppFromTempalteClick()}));this._eventHandles.push(b);b=k(n.byId("content-box"),"click",h.hitch(this,function(){f.hide();a.removeClass(e,"item-more-selected")}));this._eventHandles.push(b)}})});