define({
  "viz_settings": "Postavke vizualizacije",
  "viz_type": "Vrsta vizualizacije",
  "max_height": "Maks. visina simbola (metri)",
  "max_width": "Maks. širina simbola (metri)",
  "interval": "Intervali (milisekunde)",
  "show_percent": "Prikaži vrijednosti kao postotak svih vrijednosti",
  "show_jettrail_end_points": "Pokaži krajnje točke",
  "show_percentage_limited": "Ovo je onemogućeno jer je broj zapisa veći od 400.",
  "cycle_colors": "Automatski mijenjaj boje",
  "area_extrusion": "Izbacivanje područja",
  "bounce": "Odskok",
  "fireball": "Vatrena lopta",
  "grid_surface": " Površina mreže",
  "jet_trail": "Trag mlaznih motora",
  "point_extrusion": "Izbacivanje točke",
  "pulse": "Puls",
  "layer_settings": "Postavke sloja",
  "viz_layer": "Sloj za vizualizaciju",
  "display_field": "Polja za prikaz",
  "add_field": "Dodaj polje za vizualizaciju",
  "field": "Polje",
  "label": "Oznaka",
  "actions": "Radnje",
  "no_layers": " Nema dostupnih slojeva u odabranoj web-sceni.",
  "viz_not_supported": "Nije podržano za vrstu geometrija odabranog sloja."
});