define({
  "viz_settings": "Ustawienia wizualizacji",
  "viz_type": "Typ wizualizacji",
  "max_height": "Maks. wysokość symbolu (metry)",
  "max_width": "Maks. szerokość symbolu (metry)",
  "interval": "Interwał (milisekundy)",
  "show_percent": "Pokaż wartości jako procenty wszystkich wartości",
  "show_jettrail_end_points": "Pokaż punkty końcowe",
  "show_percentage_limited": "Wyłączono, ponieważ liczba rekordów przekracza 400.",
  "cycle_colors": "Automatycznie zmień kolory",
  "area_extrusion": "Wyniesienie obszaru",
  "bounce": "Odbicie",
  "fireball": "Kula ognia",
  "grid_surface": " Powierzchnia siatki",
  "jet_trail": "Smuga odrzutowca",
  "point_extrusion": "Wyniesienie punktu",
  "pulse": "Puls",
  "layer_settings": "Ustawienia warstwy",
  "viz_layer": "Warstwa wizualizacji",
  "display_field": "Pole wyświetlania",
  "add_field": "Dodaj pole wizualizacji",
  "field": "Pole",
  "label": "Etykieta",
  "actions": "Działania",
  "no_layers": " W wybranej scenie internetowej nie ma dostępnych warstw.",
  "viz_not_supported": "Nieobsługiwane dla typu geometrii wybranej warstwy."
});