define({
  "viz_settings": "Setări vizualizare",
  "viz_type": "Tip vizualizare",
  "max_height": "Înălţime maximă a simbolului (metri)",
  "max_width": "Lăţime maximă a simbolului (metri)",
  "interval": "Interval (milisecunde)",
  "show_percent": "Afişaţi valorile ca procent din valorile totale",
  "show_jettrail_end_points": "Afişare puncte finale",
  "show_percentage_limited": "Acesta este dezactivat deoarece numărul de înregistrări este mai mare de 400.",
  "cycle_colors": "Schimbare automată a culorilor",
  "area_extrusion": "Extruziune suprafaţă",
  "bounce": "Salt",
  "fireball": "Minge de foc",
  "grid_surface": " Suprafaţă grilă",
  "jet_trail": "Urmă de avion cu reacţie",
  "point_extrusion": "Extruziune punct",
  "pulse": "Impuls",
  "layer_settings": "Setări strat tematic",
  "viz_layer": "Strat tematic vizualizare",
  "display_field": "Câmp de afişare",
  "add_field": "Adăugare câmp de vizualizare",
  "field": "Câmp",
  "label": "Etichetă",
  "actions": "Acţiuni",
  "no_layers": " Nu este disponibil niciun strat tematic în scena web selectată.",
  "viz_not_supported": "Nu se acceptă pentru tipul de geometrie al stratului tematic selectat."
});