define({
  "viz_settings": "Definições de visualização",
  "viz_type": "Tipo de visualização",
  "max_height": "Altura máxima de símbolo (metros)",
  "max_width": "Largura máxima de símbolo (metros)",
  "interval": "Intervalo (milissegundos)",
  "show_percent": "Exibir valores como percentagem de todos os valores",
  "show_jettrail_end_points": "Exibir pontos de chegada",
  "show_percentage_limited": "Encontra-se desativado, já que o número de registos é superior a 400.",
  "cycle_colors": "Alterar cores automaticamente",
  "area_extrusion": "Extrusão de área",
  "bounce": "Bounce",
  "fireball": "Fireball",
  "grid_surface": " Superfície de grelha",
  "jet_trail": "Rasto de Jato",
  "point_extrusion": "Extrusão de pontos",
  "pulse": "Pulse",
  "layer_settings": "Configurações de Camada",
  "viz_layer": "Camada de visualização",
  "display_field": "Campo de visualização",
  "add_field": "Adicionar campo de visualização",
  "field": "Campo",
  "label": "Rótulo",
  "actions": "Acções",
  "no_layers": " Nenhuma camada disponível na cena web seleccionada.",
  "viz_not_supported": "Não suportado no tipo de geometria da camada selecionada."
});