define({
  "viz_settings": "視覚化設定",
  "viz_type": "視覚化タイプ",
  "max_height": "シンボルの最大高さ (メートル)",
  "max_width": "シンボルの最大幅 (メートル)",
  "interval": "間隔 (ミリ秒)",
  "show_percent": "すべての値に対するパーセンテージとして値を表示",
  "show_jettrail_end_points": "終点の表示",
  "show_percentage_limited": "レコード数が 400 より大きいため、これは無効化されます。",
  "cycle_colors": "色の自動変更",
  "area_extrusion": "エリアの立ち上げ",
  "bounce": "バウンド",
  "fireball": "流星",
  "grid_surface": " グリッドのサーフェス",
  "jet_trail": "ジェット機の航跡",
  "point_extrusion": "ポイントの立ち上げ",
  "pulse": "パルス",
  "layer_settings": "レイヤー設定",
  "viz_layer": "視覚化レイヤー",
  "display_field": "表示フィールド",
  "add_field": "視覚化フィールドの追加",
  "field": "フィールド",
  "label": "ラベル",
  "actions": "操作",
  "no_layers": " 選択した Web シーンには使用できるレイヤーがありません。",
  "viz_not_supported": "選択したレイヤーのジオメトリ タイプではサポートされていません。"
});