define({
  "viz_settings": "Vizualizācijas iestatījumi",
  "viz_type": "Vizualizācijas veids",
  "max_height": "Maks. simbola augstums (metri)",
  "max_width": "Maks. simbola platums (metri)",
  "interval": "Intervāls (milisekundes)",
  "show_percent": "Rādīt vērtības kā visu vērtību procentuālo attiecību",
  "show_jettrail_end_points": "Rādīt galapunktus",
  "show_percentage_limited": "Šī iespēja ir deaktivizēta, jo ierakstu skaits ir lielāks par 400.",
  "cycle_colors": "Automātiski mainīt krāsas",
  "area_extrusion": "Platības ekstrūzija",
  "bounce": "Atlēciens",
  "fireball": "Meteors",
  "grid_surface": " Režģa virsma",
  "jet_trail": "Lidmašīnas mākoņsliede",
  "point_extrusion": "Punktu ekstrūzija",
  "pulse": "Pulss",
  "layer_settings": "Slāņu iestatījumi",
  "viz_layer": "Vizualizācijas slānis",
  "display_field": "Rādīt lauku",
  "add_field": "Pievienot vizualizācijas lauku",
  "field": "Lauks",
  "label": "Nosaukums",
  "actions": "Darbības",
  "no_layers": " Izvēlētajā web scēnā nav pieejams neviens slānis.",
  "viz_not_supported": "Nav atbalstīts izvēlētā slāņa ģeometrijas tipam."
});