define({
  "viz_settings": "Impostazioni di visualizzazione",
  "viz_type": "Tipo di visualizzazione",
  "max_height": "Altezza simbolo massima (metri)",
  "max_width": "Larghezza simbolo massima (metri)",
  "interval": "Intervallo (millisecondi)",
  "show_percent": "Mostra valori come percentuale di tutti i valori",
  "show_jettrail_end_points": "Mostra punti finali",
  "show_percentage_limited": "Disabilitata perché il numero di record è maggiore di 400.",
  "cycle_colors": "Cambia automaticamente colori",
  "area_extrusion": "Estrusione area",
  "bounce": "Rimbalzo",
  "fireball": "Meteorite",
  "grid_surface": " Superficie griglia",
  "jet_trail": "Scia jet",
  "point_extrusion": "Estrusione punto",
  "pulse": "Impulso",
  "layer_settings": "Impostazioni layer",
  "viz_layer": "Layer visualizzazione",
  "display_field": "Campo di visualizzazione",
  "add_field": "Aggiungi campo di visualizzazione",
  "field": "Campo",
  "label": "Etichetta",
  "actions": "Azioni",
  "no_layers": " Nessun layer disponibile nella scena Web selezionata.",
  "viz_not_supported": "Non supportato per il tipo di geometria del layer selezionato."
});