// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:builder/plugins/widget-config/CustomWidgets.html":'\x3cdiv data-dojo-attach-event\x3d"onscroll:_onScroll"\x3e\r\n\t\x3cdiv data-dojo-attach-point\x3d"list" class\x3d"list widget-list" data-dojo-attach-event\x3d"onclick:_onClick"\x3e\x3c/div\x3e\r\n\t\x3cdiv data-dojo-type\x3d"jimu/dijit/LoadingIndicator" data-dojo-attach-point\x3d"loading" data-dojo-props\x3d\'hidden:true\'\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./CustomWidgets.html dojo/Evented dojo/query dojo/_base/lang dojo/_base/array dojo/_base/html jimu/utils jimu/portalUtils jimu/portalUrlUtils jimu/dijit/LoadingIndicator".split(" "),function(h,k,l,m,n,p,e,c,f,d,g,q,r){return h([k,l,m,p],{templateString:n,baseClass:"custom-widgets",query:null,nls:null,type:"AppBuilder Extension",portalUrl:null,hidden:!1,postMixInProperties:function(){this.nls=
window.jimuNls.itemSelector},postCreate:function(){this.inherited(arguments);this.portalUrl=r.getStandardPortalUrl(this.portalUrl);this.portal=q.getPortal(this.portalUrl);this.baseQ='type:"'+this.type+'" AND typekeywords:"Widget,'+window.appInfo.appType+'"';"HTML"===window.appInfo.appType.toUpperCase()&&(this.baseQ+=' -typekeywords:"HTML3D"');this.hidden&&this.hide()},filterLocally:function(a){e(".widget-node",this.domNode).forEach(c.hitch(this,function(b){a(b.item)?d.removeClass(b,"hidden"):d.addClass(b,
"hidden")}))},queryItems:function(a){a=a||{};this.loading.show();this.clear();c.mixin(this.query,a);this.query.start=1;this.query.q=a.q?this.baseQ+" AND "+a.q:this.baseQ;return this.portal.queryItems(this.query).then(c.hitch(this,function(a){if(this.domNode)return this.domNode&&this.loading.hide(),this.query.start=a.nextStart,this._createItemsNode(a)}),c.hitch(this,function(a){console.error(a);this.domNode&&this.loading.hide()}))},_createItemsNode:function(a){a=a.results;var b=this.type.toLowerCase();
a=f.filter(a,c.hitch(this,function(a){return(a.type&&a.type.toLowerCase()||"")===b}));f.forEach(a,c.hitch(this,function(a){this._createItemNode(a)}));return a},_createItemNode:function(a){var b=d.toDom('\x3cdiv class\x3d"widget-node"\x3e\x3cdiv class\x3d"box"\x3e\x3cimg class\x3d"icon"\x3e\x3ca target\x3d"_blank" class\x3d"detail-icon"\x3e\x3c/a\x3e\x3c/div\x3e\x3cdiv class\x3d"box-selected"\x3e\x3c/div\x3e\x3cdiv class\x3d"label"\x3e\x3c/div\x3e\x3c/div\x3e');b.item=a;e("img",b)[0].src=g.widgetJson.getFolderUrlFromItem(a)+
"images/icon.png";var c=e(".label",b)[0];c.innerHTML=a.title||"";c.title=a.title||"";c=e(".detail-icon",b)[0];c.href=a.detailsPageUrl;c.title=this.nls.viewItemDetails||"View item details";d.place(b,this.list)},clear:function(){this.query={q:this.baseQ,sortField:"title",sortOrder:"asc",num:100,start:1};d.empty(this.list)},_onClick:function(a){a=a.target||a.srcElement;var b=null;if(b=d.hasClass(a,"widget-node")?a:g.getAncestorDom(a,function(a){return d.hasClass(a,"widget-node")},this.list))e(".official-section .jimu-state-selected",
this.widgetDomNode).removeClass("jimu-state-selected"),"addBtn"===this.fromNode.type?d.toggleClass(b,"jimu-state-selected"):(e(".jimu-state-selected",this.domNode).removeClass("jimu-state-selected"),d.addClass(b,"jimu-state-selected"))},_onScroll:function(){this._isScrollToBottom(this.domNode)},_isScrollToBottom:function(a){return g.isScrollToBottom(a)},getSelectedWidgetItems:function(){var a=e(".widget-node.jimu-state-selected",this.domNode).filter(c.hitch(this,function(a){return!d.hasClass(a,"hidden")}));
return f.map(a,c.hitch(this,function(a){return a.item}))},isVisible:function(){return!d.hasClass(this.domNode,"hidden")},show:function(){d.removeClass(this.domNode,"hidden")},hide:function(){d.addClass(this.domNode,"hidden")}})});