// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/html dojo/_base/array dojo/topic dojo/aspect dojo/Evented dojo/query dojo/NodeList-dom dijit/_WidgetBase ./MoveableNode ./LinkList jimu/utils".split(" "),function(q,f,e,r,g,l,v,m,A,t,w,x,y){function n(a){var b={};isFinite(a.l)&&(b.left=a.l+"px");isFinite(a.t)&&(b.top=a.t+"px");isFinite(a.w)&&(b.width=a.w+"px");isFinite(a.h)&&(b.height=a.h+"px");return b}var h,u=window.Sortable,z=q([t],{box:null,marginBox:null,postCreate:function(){this.inherited(arguments);
this.domNode=e.create("div",{"class":"node-margin"});this.type="addBtn"===this.node.type?"addMargin":"margin"}});return q([t,v],{postCreate:function(){this.nodeList=new x({name:this.name});this.own(g.subscribe("widgetChoosePageOk",f.hitch(this,this._onWidgetChoosePageOk)));this.own(g.subscribe("widgetSettingPageOk",f.hitch(this,this._onWidgetSettingPageOk)))},startup:function(){this.inherited(arguments);this.settings&&this.initNodes()},setSettings:function(a){this.settings=f.clone(a);this.initNodes()},
setAppConfig:function(a){this.appConfig=a},addWidget:function(a){a=this.createMoveableNode("widget",a);this.nodeList.insertNode(a);this.placeNodes()},createMoveableNode:function(a,b){var c=f.clone(this.box);c.h=Infinity;var d=new w({type:a,w:74,h:118,setting:b,listName:this.name,parentBox:c,nls:this.nls,folderUrl:this.folderUrl,appConfig:this.appConfig});e.place(d.domNode,this.domNode);d.startup();this.bindMoveEvent(d);"group"===a&&(l.after(d,"openGroup",f.hitch(this,this.openGroup,d)),l.after(d,
"closeGroup",f.hitch(this,this.closeGroup,d)));d.on("removeNode",f.hitch(this,function(){"poolWidgets"===this.name||"groupOnScreen"===this.name?(d.gnode?(this.nodeList.removeNode(d),this._reopenGroup()):this.nodeList.removeNode(d),this.placeNodes(),"poolWidgets"===this.name?this.publishPoolChangeEvent():g.publish("groupChanged",d.gnode.setting)):(d.setting.uri="",d.setting.label=this.nls.defaultWidgetLabel,d.setting.name=void 0,d.setting.placeholderIndex="?",d.setting.config=void 0,this.label=this.nls.defaultWidgetLabel,
y.widgetJson.removeManifestFromWidgetJson(d.setting),g.publish("widgetChanged",d.setting))}));d.on("clickOpenAtStart",f.hitch(this,function(){var a={id:d.setting.id,openAtStart:!d.setting.openAtStart};a.isOnScreen="poolWidgets"===this.name?!1:!0;g.publish("openAtStartChange",a)}));this.createMarginNode(d);return d},openGroup:function(a){var b,c,d,e,p,g,k;this.openedGNode&&this.openedGNode!==a&&this.openedGNode.closeGroup(this.openedGNode);b=a.setting.widgets;p=this.getNodePosition(this.nodeList.getNodeIndex(a)).r;
g=this._groupCanAddMoreWidget(a)?Math.ceil((b.length+1)/h):Math.ceil(b.length/h);c=p*h+1;d=this.nodeList.getNodeByIndex(c);for(e=this.nodeList.getCount()+1;e<c;e++)k=this.createMoveableNode("empty"),k.gnode=a,this.nodeList.insertNode(k,d);this.openedGNode=a;this.openedGNode.panelRow=p+1;this.createGroupPanel(p+1,g);b.forEach(f.hitch(this,function(b){b=this.createMoveableNode("widget",b);b.gnode=a;this.nodeList.insertNode(b,d)}));"groupOnScreen"===this.name?this._groupCanAddMoreWidget(a)?(e=this.createMoveableNode("addBtn"),
e.gnode=a,this.nodeList.insertNode(e,d),b=h*g-b.length-1):b=h*g-b.length:b=h*g-b.length;for(e=0;e<b;e++)k=this.createMoveableNode("empty"),k.gnode=a,this.nodeList.insertNode(k,d);this.placeNodes();this.emit("groupOpened")},_groupCanAddMoreWidget:function(a){return"undefined"===typeof a.setting.maxWidgets||a.setting.maxWidgets>a.setting.widgets.length},createGroupPanel:function(a,b){a={t:118*(a-1)-10,h:118*b+0*(b-1),w:94*h-20+20};window.isRTL?a.r=10:a.l=10;this.groupPanel=e.create("div",{"class":"widget-group-panel",
style:n(a)},this.domNode);a=(this.openedGNode.pos.c-1)%h*94+37;window.isRTL&&(a=1===this.openedGNode.pos.c?94*h-37:(h-this.openedGNode.pos.c+1)%h*94-37);e.create("div",{"class":"group-triangle",style:{left:a+"px"}},this.groupPanel);this.groupPanel.type="panel"},closeGroup:function(a){var b=[];a.setting.widgets=[];this.nodeList.visitNodes(f.hitch(this,function(c){c.gnode===a&&("empty"!==c.type&&"addBtn"!==c.type&&a.setting.widgets.push(c.setting),b.push(c))}));b.forEach(f.hitch(this,function(a){this.nodeList.removeNode(a)}));
0===a.setting.widgets.length?"poolWidgets"===this.name&&this.nodeList.removeNode(a):a.updateSmallWidgets();this.placeNodes();e.destroy(this.groupPanel);this.openedGNode=null;this.emit("groupClosed")},initNodes:function(){this.box=e.getContentBox(this.domNode);this.position=e.position(this.domNode,!0);h=Math.floor(this.box.w/94);this.destroyShadowNode();var a=this.settings;"notRemoveableWidgetOnScreen"===this.name?a=a.sort(function(a,b){return a.label.localeCompare(b.label)}):"removeableWidgetOnScreen"===
this.name?1<a.length&&(a=a.sort(function(a,b){var c;r.some(["left","top","right","bottom"],function(d){if(!isNaN(a.position[d])){if(isNaN(b.position[d]))return c=1,!0;if(a.position[d]!==b.position[d])return c=a.position[d]-b.position[d],!0}else if(!isNaN(b.position[d]))return c=-1,!0});return isNaN(c)?0:c})):a=a.sort(function(a,b){return a.index-b.index});var b;this.openedGNode&&(b=this.openedGNode.label,this.closeGroup(this.openedGNode));this.nodeList.destroyAllNodes();"poolWidgets"===this.name&&
(this.addBtn=this.createMoveableNode("addBtn"),this.nodeList.insertNode(this.addBtn));a.forEach(f.hitch(this,function(a,b){if(a=a.widgets?this.createMoveableNode("group",a):a.uri?this.createMoveableNode("widget",a):this.createMoveableNode("placeholder",a))e.setAttr(a.domNode,"data-id",b),this.nodeList.insertNode(a)}));"poolWidgets"===this.name&&this.nodeList.insertNode(this.createMoveableNode("empty"));"removeableWidgetOnScreen"===this.name&&u?(this.sortableNodes&&this.sortableNodes.destroy(),this.sortableNodes=
u.create(this.domNode,{sort:!0,disabled:!1,draggable:".widget-node",animation:150,onSort:f.hitch(this,function(){var b=[],d;this.sortableNodes.toArray().forEach(function(c,e){d=f.clone(a[+c]);d.position=f.clone(a[e].position);b.push(d)});g.publish("onScreenOrderChanged",b)})})):this.placeNodes();b&&(b=this.nodeList.getNodeByLabel(b))&&(this.openGroup(b),b.status="open")},getListHeight:function(){var a=0;this.nodeList.visitNodes(function(b){a=Math.max(b.pos.r,a)});return 118*a},_removeActive:function(){m(".node-margin-active",
this.domNode).removeClass("node-margin-active");m(".empty-node-active",this.domNode).removeClass("empty-node-active");m(".node-active",this.domNode).removeClass("node-active")},bindMoveEvent:function(a){"addBtn"!==a.type&&a.dnd&&(l.after(a.dnd,"onMove",f.hitch(this,function(b,c,d){b=this.getMousePosition(d);this.mouseNode=this.getNodeByMousePosition(a,b);this._removeActive();this.mouseNode&&"margin"===this.mouseNode.type?e.addClass(this.mouseNode.domNode,"node-margin-active"):this.mouseNode&&"empty"===
this.mouseNode.type?e.addClass(this.mouseNode.domNode,"empty-node-active"):!this.mouseNode||"group"!==this.mouseNode.type&&"widget"!==this.mouseNode.type||e.addClass(this.mouseNode.domNode,"node-active")}),!0),l.after(a.dnd,"onMoveStart",f.hitch(this,function(){this.destroyShadowNode();this.createShadowNode(a);e.setStyle(a.boxNode,"cursor","move")}),!0),l.after(a.dnd,"onMoveStop",f.hitch(this,this._onMoveStop,a),!0))},_onMoveStop:function(a){var b=!1,c=[];e.setStyle(a.boxNode,"cursor","pointer");
this.mouseNode&&(a===this.mouseNode?console.log("move to the same node"):"margin"===this.mouseNode.type?(this.moveNodeToMargin(a,this.mouseNode),"groupOnScreen"===this.name&&c.push(a.gnode.setting),b=!0):"empty"===this.mouseNode.type?this.mouseNode.gnode&&"group"===a.type?console.log("not allow move group to opened group, revert"):(this.moveNodeToEmpty(a,this.mouseNode),"groupOnScreen"===this.name&&c.push(a.gnode.setting),b=!0):"group"===this.mouseNode.type?"group"===a.type?console.log("not allow move group to closed group, revert"):
"open"===this.mouseNode.status?console.log("please put widget into the opened group panel"):!1===a.setting.inPanel?this._showOffPanelToGroupError():a.gnode&&a.gnode===this.mouseNode?console.log("the moving widget is already in the group"):this.mouseNode.setting.maxWidgets&&this.mouseNode.setting.widgets&&this.mouseNode.setting.widgets.length+1>this.mouseNode.setting.maxWidgets?this._showGroupExceedMaxError(this.mouseNode.setting):(this.moveWidgetToGroup(a,this.mouseNode),"groupOnScreen"===this.name&&
(c.push(a.gnode.setting),c.push(this.mouseNode.setting)),b=!0):"widget"===this.mouseNode.type&&("group"===a.type?console.log("not allow move group to widget, revert"):!1===a.setting.inPanel||!1===this.mouseNode.setting.inPanel?this._showOffPanelToGroupError():a.gnode||this.mouseNode.gnode?console.log("can not nest group"):(this.moveWidgetToWidget(a,this.mouseNode),b=!0)),this._reopenGroup());this.destroyShadowNode();b&&("poolWidgets"===this.name?this.publishPoolChangeEvent():0<c.length&&this.publishOnScreenGroupsChangeEvent());
this.placeNodes()},_reopenGroup:function(){if(this.openedGNode){var a=this.openedGNode;this.closeGroup(a);this.nodeList.isExist(a)&&this.openGroup(a)}},getNodePosition:function(a){var b={},c;c=Math.ceil(a/h);a%=h;0===a&&(a=h);b.t=118*(c-1);var d=94*(a-1)+20;b.l=window.isRTL?this.box.w-d-74:d;b.w=74;b.h=118;b.r=c;b.c=a;return b},getMarginNodePosition:function(a){var b={};a=a.pos;b.l=window.isRTL?a.l+74+10:a.l-10-2.5;b.t=a.t;b.w=5;b.h=118;return b},createMarginNode:function(a){var b=new z({label:a.label,
node:a});e.place(b.domNode,this.domNode);return a.margin=b},getMousePosition:function(a){return{x:a.pageX-this.position.x,y:a.pageY-this.position.y}},moveNodeToMargin:function(a,b){b=this.getNodeByMarginNode(b);console.log("moveNodeToMargin");m(".node-margin-active",this.domNode).removeClass("node-margin-active");b.gnode&&!a.gnode?a.gnode=b.gnode:!b.gnode&&a.gnode&&(a.gnode=null);this.nodeList.moveNode(a,b)},moveNodeToEmpty:function(a,b){m(".empty-node-active",this.domNode).removeClass("empty-node-active");
b.gnode&&!a.gnode?a.gnode=b.gnode:!b.gnode&&a.gnode&&(a.gnode=null);this.nodeList.moveNode(a,b)},getNodeByMarginNode:function(a){var b;this.nodeList.visitNodes(function(c){c.margin===a&&(b=c)});return b},placeNodes:function(){var a,b;this.nodeList.visitNodes(f.hitch(this,function(c,d){a=this.getNodePosition(d);c.pos=a;e.setStyle(c.domNode,n(a));b=this.getMarginNodePosition(c);c.margin.pos=b;e.setStyle(c.margin.domNode,n(b))}));this.nodeList.printNodeList()},moveWidgetToGroup:function(a,b){a&&a.setting&&
delete a.setting.openAtStart;b.addWidget(a);this.nodeList.removeNode(a)},moveWidgetToWidget:function(a,b){var c;a&&a.setting&&delete a.setting.openAtStart;c=this.createMoveableNode("group",{label:this._getGroupLabel(),widgets:[a.setting,b.setting]});this.nodeList.insertNode(c,b);this.nodeList.removeNode(a);this.nodeList.removeNode(b)},createShadowNode:function(a){this.shadowNode=e.create("div",{"class":"node-shadow",style:n(e.getMarginBox(a.domNode))},this.domNode)},destroyShadowNode:function(){this.shadowNode&&
e.destroy(this.shadowNode)},getNodeByMousePosition:function(a,b){var c;this.nodeList.visitNodes(function(d){if("addBtn"!==d.type){if(b.x>d.pos.l+10&&b.x<d.pos.l+d.pos.w-10&&b.y>d.pos.t+10&&b.y<d.pos.t+d.pos.h-10&&d!==a)return c=d,!0;if(b.x>d.margin.pos.l&&b.x<d.margin.pos.l+d.margin.pos.w&&b.y>d.margin.pos.t&&b.y<d.margin.pos.t+d.margin.pos.h&&d.margin!==a)return c=d.margin,!0}});return c},_getGroupLabel:function(){var a=-1;this.appConfig.visitElement(f.hitch(this,function(b){if(b.widgets)if(b.label===
this.nls.newGroup)a=0;else if(b.label.startWith(this.nls.newGroup)){var c=b.label.lastIndexOf("_");-1<c&&(b=parseInt(b.label.substr(c+1,b.label.length),10),a=Math.max(a,b))}}));return-1===a?this.nls.newGroup:this.nls.newGroup+"_"+(a+1)},_showOffPanelToGroupError:function(){console.log("Off panel widget is not allowed in group.");this.emit("offpanel-group-error")},_showGroupExceedMaxError:function(a){this.emit("group-exceed-max-error",a)},_onWidgetChoosePageOk:function(a,b){if(b.listName===this.name)if(1===
a.length){var c;"addBtn"===b.type?c=a[0]:"group"===b.type?c=a[0]:(c=f.clone(b.setting),f.mixin(c,a[0]));g.publish("editWidget",c,b)}else"poolWidgets"===this.name?(r.forEach(a,function(a){this.addWidget(a)},this),this.publishPoolChangeEvent()):("addBtn"===b.type?c=f.clone(this.appConfig.getConfigElementById(b.gnode.setting.id)):"group"===b.type&&(c=f.clone(this.appConfig.getConfigElementById(b.setting.id))),c.widgets=c.widgets.concat(a),g.publish("groupChanged",c))},_onWidgetSettingPageOk:function(a,
b){if(b.listName===this.name)if(a.id)g.publish("widgetChanged",a);else if("poolWidgets"===this.name)this.addWidget(a),this.publishPoolChangeEvent();else{var c;"addBtn"===b.type?c=f.clone(this.appConfig.getConfigElementById(b.gnode.setting.id)):"group"===b.type&&(c=f.clone(this.appConfig.getConfigElementById(b.setting.id)));c.widgets.push(a);c.label||(c.label=this._getGroupLabel());g.publish("groupChanged",c)}},publishPoolChangeEvent:function(){var a=[],b=[];this.nodeList.visitNodes(function(c,d){"widget"!==
c.type||c.gnode?"group"===c.type&&(c.setting.index=d,a.push(c.setting)):(c.setting.index=d,b.push(c.setting))});g.publish("widgetPoolChanged",{widgets:b,groups:a,controllerId:this.controller.id})},publishOnScreenGroupsChangeEvent:function(){var a=[];this.nodeList.visitNodes(function(b){"group"===b.type&&a.push(b.setting)});g.publish("onScreenGroupsChanged",{groups:a})}})});