define({
  "viz_settings": "Nastavitve vizualizacije",
  "viz_type": "Tip vizualizacije",
  "max_height": "Maksimalna višina simbola (v metrih)",
  "max_width": "Maksimalna širina simbola (v metrih)",
  "interval": "Interval (milisekunde)",
  "show_percent": "Pokaži vrednosti kot odstotek vseh vrednosti",
  "show_jettrail_end_points": "Pokaži končne točke",
  "show_percentage_limited": "To je onemogočeno, ker je število zapisov večje od 400.",
  "cycle_colors": "Samodejno spremeni barve",
  "area_extrusion": "Površinska ekstruzija",
  "bounce": "Poskok",
  "fireball": "Ognjena krogla",
  "grid_surface": " Površje mreže",
  "jet_trail": "Sled reaktivnega letala",
  "point_extrusion": "Cilinder",
  "pulse": "Koncentrični krogi",
  "layer_settings": "Nastavitve sloja",
  "viz_layer": "Vizualizacijski sloj",
  "display_field": "Prikaži polje",
  "add_field": "Dodaj vizualizacijsko polje",
  "field": "Polje",
  "label": "Napis",
  "actions": "Dejanja",
  "no_layers": " V izbranem spletnem 3D-prizoru sloji niso na voljo.",
  "viz_not_supported": "Ni podprto za geometrijski tip izbranega sloja."
});