define({
  "viz_settings": "Visualisatie-instellingen",
  "viz_type": "Visualisatietype",
  "max_height": "Max symboolhoogte (meter)",
  "max_width": "Max symboolbreedte (meter)",
  "interval": "Interval (milliseconden)",
  "show_percent": "Waarden weergeven als percentage van alle waarden",
  "show_jettrail_end_points": "Eindpunten tonen",
  "show_percentage_limited": "Dit is uitgeschakeld omdat het aantal records groter is dan 400.",
  "cycle_colors": "Automatisch van kleur veranderen",
  "area_extrusion": "Gebiedsextrusie",
  "bounce": "Bounce",
  "fireball": "Fireball",
  "grid_surface": " Rasteroppervlak",
  "jet_trail": "Jettrail",
  "point_extrusion": "Puntextrusie",
  "pulse": "Pulse",
  "layer_settings": "Laaginstellingen",
  "viz_layer": "Visualisatielaag",
  "display_field": "Weergaveveld",
  "add_field": "Visualisatieveld toevoegen",
  "field": "Veld",
  "label": "Label",
  "actions": "Acties",
  "no_layers": " Geen lagen beschikbaar in geselecteerde webscene.",
  "viz_not_supported": "Niet ondersteund voor geometrietype van geselecteerde laag."
});