define({
  "viz_settings": "Visualiseringsinställningar",
  "viz_type": "Visualiseringstyp",
  "max_height": "Maximal symbolhöjd (meter)",
  "max_width": "Maximal symbolbredd (meter)",
  "interval": "Intervall (millisekunder)",
  "show_percent": "Visa värden som procentandelar av alla värden",
  "show_jettrail_end_points": "Visa slutpunkter",
  "show_percentage_limited": "Detta är inaktiverat eftersom antalet poster är större än 400.",
  "cycle_colors": "Ändra färger automatiskt",
  "area_extrusion": "Områdesprojektion",
  "bounce": "Hopp",
  "fireball": "Eldklot",
  "grid_surface": " Rutnätsyta",
  "jet_trail": "Kondensationsstrimma",
  "point_extrusion": "Punktprojektion",
  "pulse": "Puls",
  "layer_settings": "Lagerinställningar",
  "viz_layer": "Visualiseringslager",
  "display_field": "Visningsfält",
  "add_field": "Lägg till visualiseringsfält",
  "field": "Fält",
  "label": "Etikett",
  "actions": "Åtgärder",
  "no_layers": " Inga lager är tillgängliga i den valda webbscenen.",
  "viz_not_supported": "Stöds inte för det valda lagrets geometrityp."
});