define({
  "viz_settings": "시각화 설정",
  "viz_type": "시각화 유형",
  "max_height": "최대 심볼 높이(미터)",
  "max_width": "최대 심볼 너비(미터)",
  "interval": "간격(밀리초)",
  "show_percent": "모든 값의 백분율로 값 표시",
  "show_jettrail_end_points": "끝점 표시",
  "show_percentage_limited": "레코드 수가 400보다 크므로 비활성화됩니다.",
  "cycle_colors": "색상 자동 변경",
  "area_extrusion": "영역 돌출",
  "bounce": "바운스",
  "fireball": "파이어볼",
  "grid_surface": " 그리드 표면",
  "jet_trail": "제트 트레일",
  "point_extrusion": "포인트 돌출",
  "pulse": "펄스",
  "layer_settings": "레이어 설정",
  "viz_layer": "시각화 레이어",
  "display_field": "디스플레이 필드",
  "add_field": "시각화 필드 추가",
  "field": "필드",
  "label": "레이블",
  "actions": "작업",
  "no_layers": " 선택한 웹 씬에는 사용 가능한 레이어가 없습니다.",
  "viz_not_supported": "선택한 레이어의 지오메트리 유형을 지원하지 않습니다."
});