define({
  "viz_settings": "Pengaturan visualisasi",
  "viz_type": "Jenis visualisasi",
  "max_height": "Tinggi Simbol Maks (meter)",
  "max_width": "Lebar simbol Maks (meter)",
  "interval": "Interval (milidetik)",
  "show_percent": "Perlihatkan nilai sebagai persentase semua nilai",
  "show_jettrail_end_points": "Tampilkan titik akhir",
  "show_percentage_limited": "Ini dinonaktifkan karena jumlah record lebih besar dari 400.",
  "cycle_colors": "Ubah warna secara otomatis",
  "area_extrusion": "Ekstrusi area",
  "bounce": "Bounce",
  "fireball": "Fireball",
  "grid_surface": " Permukaan grid",
  "jet_trail": "Jejak jet",
  "point_extrusion": "Ekstrusi titik",
  "pulse": "Pulse",
  "layer_settings": "Pengaturan layer",
  "viz_layer": "Layer visualisasi",
  "display_field": "Kolom tampilan",
  "add_field": "Tambahkan kolom visualisasi",
  "field": "Kolom",
  "label": "Label",
  "actions": "Tindakan",
  "no_layers": " Tidak tersedia layer pada web scene terpilih.",
  "viz_not_supported": "Tidak didukung untuk jenis geometri dari layer terpilih."
});