define({
  root: ({
    "viz_settings": "Visualization settings",
    "viz_type": "Visualization type",
    "max_height": "Max Symbol height (meters)",
    "max_width": "Max symbol width (meters)",
    "interval": "Interval (milliseconds)",
    "show_percent": "Show values as percentage of all values",
    "show_jettrail_end_points": "Show end points",
    "show_percentage_limited": "This is disabled since the number of records is larger than 400.",
    "cycle_colors": "Automatically change colors",
    "area_extrusion": "Area extrusion",
    "bounce": "Bounce",
    "fireball": "Fireball",
    "grid_surface": " Grid surface",
    "jet_trail": "Jet trail",
    "point_extrusion": "Point extrusion",
    "pulse": "Pulse",
    "layer_settings": "Layer settings",
    "viz_layer": "Visualization layer",
    "display_field": "Display field",
    "add_field": "Add visualization field",
    "field": "Field",
    "label": "Label",
    "actions": "Actions",
    "no_layers": " No layers available in selected web scene.",
    "viz_not_supported": "Not supported for geometry type of selected layer."
  }),
  "ar": 1,
  "bs": 1,
  "ca": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "hu": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
