define({
  "viz_settings": "Görselleştirme ayarları",
  "viz_type": "Görselleştirme türü",
  "max_height": "Maks sembol yüksekliği (metre)",
  "max_width": "Maks sembol genişliği (metre)",
  "interval": "Aralık (mili saniye)",
  "show_percent": "Değerleri tüm değerlerin yüzdesi olarak göster",
  "show_jettrail_end_points": "Uç noktaları göster",
  "show_percentage_limited": "Kayıt sayısı 400'den büyük olduğu için bu özellik devre dışıdır.",
  "cycle_colors": "Renkleri otomatik değiştir",
  "area_extrusion": "Alan uzatma",
  "bounce": "Geri Dönüş",
  "fireball": "Ateş Topu",
  "grid_surface": " Kılavuz yüzeyi",
  "jet_trail": "Jet izi",
  "point_extrusion": "Nokta uzatma",
  "pulse": "Darbe",
  "layer_settings": "Katman ayarları",
  "viz_layer": "Görselleştirme katmanı",
  "display_field": "Alan görüntüle",
  "add_field": "Görselleştirme alanı ekle",
  "field": "Alan",
  "label": "Etiket",
  "actions": "İşlemler",
  "no_layers": " Seçilen web görünümünde katman yok.",
  "viz_not_supported": "Seçili katmanın geometri türü için desteklenmiyor."
});