define({
  "viz_settings": "Configuración de visualización",
  "viz_type": "Tipo de visualización",
  "max_height": "Altura máxima de símbolo (metros)",
  "max_width": "Ancho máximo de símbolo (metros)",
  "interval": "Intervalo (milisegundos)",
  "show_percent": "Mostrar valores como porcentajes de todos los valores",
  "show_jettrail_end_points": "Mostrar extremos",
  "show_percentage_limited": "Esto está deshabilitado debido a que el número de registros es mayor que 400.",
  "cycle_colors": "Cambiar colores automáticamente",
  "area_extrusion": "Extrusión de área",
  "bounce": "Rebote",
  "fireball": "Bola de fuego",
  "grid_surface": " Superficie de cuadrícula",
  "jet_trail": "Estela de reactor",
  "point_extrusion": "Extrusión de punto",
  "pulse": "Pulso",
  "layer_settings": "Configuración de capa",
  "viz_layer": "Capa de visualización",
  "display_field": "Mostrar campo",
  "add_field": "Agregar campo de visualización",
  "field": "Campo",
  "label": "Etiqueta",
  "actions": "Acciones",
  "no_layers": " No hay capas disponibles en la escena web seleccionada.",
  "viz_not_supported": "No es compatible con el tipo de geometría de la capa seleccionada."
});