define({
  "viz_settings": "Thiết lập trực quan hóa",
  "viz_type": "Loại trực quan hóa",
  "max_height": "Chiều cao ký hiệu tối đa (mét)",
  "max_width": "Chiều rộng ký hiệu tối đa (mét)",
  "interval": "Khoảng thời gian (mili giây)",
  "show_percent": "Hiện giá trị dưới dạng phần trăm tất cả giá trị",
  "show_jettrail_end_points": "Hiển thị các điểm cuối",
  "show_percentage_limited": "Tính năng này đã bị vô hiệu hóa do số lượng bản ghi lớn hơn 400.",
  "cycle_colors": "Tự động đổi màu",
  "area_extrusion": "Vùng nhô ra",
  "bounce": "Bật lên",
  "fireball": "Cầu lửa",
  "grid_surface": " Bề mặt lưới",
  "jet_trail": "Vệt khói máy bay",
  "point_extrusion": "Mức trồi sụt điểm",
  "pulse": "Xung",
  "layer_settings": "Thiết lập lớp",
  "viz_layer": "Lớp trực quan hóa",
  "display_field": "Hiển thị trường",
  "add_field": "Thêm trường trực quan hóa",
  "field": "Trường",
  "label": "Nhãn",
  "actions": "Các hành động",
  "no_layers": " Không có lớp khả dụng trong web scene được chọn.",
  "viz_not_supported": "Không hỗ trợ loại hình học của lớp được chọn."
});