define({
  "viz_settings": "Postavke vizuelizacije",
  "viz_type": "Tip vizuelizacije",
  "max_height": "Maksimalna visina simbola (u metrima)",
  "max_width": "Maksimalna širina simbola (u metrima)",
  "interval": "Interval (u milisekundama)",
  "show_percent": "Prikaži vrednosti kao procenat svih vrednosti",
  "show_jettrail_end_points": "Prikaži krajnje tačke",
  "show_percentage_limited": "Ovo je onemogućeno pošto je broj zapisa veći od 400.",
  "cycle_colors": "Automatski menjaj boje",
  "area_extrusion": "Površina ekstruzije",
  "bounce": "Odskok",
  "fireball": "Vatrena lopta",
  "grid_surface": " Površina mreže",
  "jet_trail": "Mlazni trag",
  "point_extrusion": "Istiskivanje tačke",
  "pulse": "Puls",
  "layer_settings": "Postavke sloja",
  "viz_layer": "Sloj vizuelizacije",
  "display_field": "Prikaži polje",
  "add_field": "Dodaj polje vizuelizacije",
  "field": "Polje",
  "label": "Oznaka",
  "actions": "Radnje",
  "no_layers": " Nema dostupnih slojeva u izabranoj veb sceni.",
  "viz_not_supported": "Nije podržano za tip geometrije izabranog sloja."
});