define({
  "viz_settings": "Настройки визуализации",
  "viz_type": "Тип визуализации",
  "max_height": "Макс. высота символа (в метрах)",
  "max_width": "Макс. ширина символа (в метрах)",
  "interval": "Интервал (миллисекунды)",
  "show_percent": "Отображать значения как процент всех значений",
  "show_jettrail_end_points": "Показать конечные точки",
  "show_percentage_limited": "Это отключено, так как число записей больше 400.",
  "cycle_colors": "Изменять цвета автоматически",
  "area_extrusion": "Вытягивание полигона",
  "bounce": "Bounce",
  "fireball": "Fireball",
  "grid_surface": " Поверхность Grid",
  "jet_trail": "Струящийся след",
  "point_extrusion": "Вытягивание точки",
  "pulse": "Pulse",
  "layer_settings": "Настройки слоя",
  "viz_layer": "Слой визуализации",
  "display_field": "Поле отображения",
  "add_field": "Добавить поле визуализации",
  "field": "Поле",
  "label": "Подпись",
  "actions": "Действия",
  "no_layers": " Нет слоев, доступных для выбранной веб-сцены.",
  "viz_not_supported": "Не поддерживается для типа геометрии выбранного слоя."
});