// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({root:{ok:"OK",cancel:"Cancel",save:"Save",close:"Close",doNotSave:"Don't Save",saved:"Saved",saving:"Saving",emptyMessage:"Please select widget.",chooseWidget:"Choose Widget",deleting:"Deleting",duplicating:"Duplicating",uploading:"Uploading",updating:"Updating",change:"Update thumbnail",appIdTip:"Provide the App ID for Web AppBuilder registered in the portal you specify above",appIdPlaceHolder:"App ID",appIdError:"This is not a valid App ID.",duplicateError:"Failed to duplicate the app.",
duplicateUrlError:"The app is successfully duplicated, but failed to update the URL.",addItemError:"Failed to add item.",addItemUnsuccess:"AddItem responses unsuccessfully",createUrlError:"The app is successfully created, but failed to update the URL.",createError:"Failed to create the app.",createCodeAttachmentError:'The app is successfully created, but failed to add "Code Attachment".',saveAsError:"Failed to save as a new app.",titleExist:"The Web Mapping Application titled '${TITLE}' is already available in your content. Please choose a different title.",
tip:"Specify the URL to your ArcGIS Online organization or Portal for ArcGIS",continueBtn:"Continue",example:"Example",missingMessage:"URL is required.",invalidMessage:"Invalid Portal URL",faq:"FAQs",errPrefix:"Unable to access ",errRemind:"A server with the specified hostname could not be found.",errOrg:"Please enter the full URL of your ArcGIS Online organization or Portal for ArcGIS, for example, ",errorMessage:"Incorrect username or password",portalError:"Portal error",username:"Username",password:"Password",
forgot:"Forgot password",remember:"Remember username and password",signin:"Sign in",back:"Back",next:"Next",con:"Continue",namedUserTip:"Web AppBuilder for ArcGIS does not support public accounts. Please use an organizational account to log in.",signingIn:"Signing in",registeringAppID:"Registering App ID",here:"here",appIdTip1:"Since this is the first time for Web AppBuilder to work with the organization or portal you just specified, an App ID is required to support OAuth2 signin process.",appIdTip2:"Provide your username and password for your organization or portal. Once succeeded, Web AppBuilder will auto-register an App ID, along with a new web mapping application item named 'Web AppBuilder for ArcGIS' in My Content. Please don't delete or change the item. For more information about registering App ID, refer ",
nameLabel:"Title",nameLabelPlaceHolder:"Enter a title for the app",tagsLabel:"Tags:",summaryLabel:"Description",summaryLabelPlaceHolder:"Description of the app",saveFolderLabel:"Save in the folder:",thumbnailLabel:"Thumbnail:",shareSameLevel:"Share this app in the same way as the map",addTags:"Add tag(s)",noTagsFound:"No match for the existing tags.",title2:"Export as web app template",rightPartHead:"Set configurable parameters to the template",rightPartSubhead:"Parameter categories",rightPartHead2:"Template JSON code",
viewJsonCode:"View JSON code",viewJsonBack:"Back to Settings",download:"Download",update:"Update",unSaveMeg:"Want to save your changes?",saveSuccessMeg:"Saved successfully",appNameTitle:"App name: ",fieldLabel:"Field label:",fieldType:"Field type:",typeSelectString:"String",typeSelectBoolean:"Boolean",typeSelectNumber:"Number",typeSelectOptions:"Options",typeSelectColor:"Color",tooltip:"Tooltip:",placeholder:"Placeholder:",textBoxType:"Text box type:",textBoxTypeRichtext:"richtext",textBoxTypeTextarea:"textarea",
textBoxTypeTextbox:"textbox",minvalue:"Min value:",maxvalue:"Max value:",places:"Places:",addNewOption:"Add a new option",labelStr:"Label:",value:"Value:",templateTitle:"You are going to export current parameter settings and create a new web app template item in your portal.",explain1:"The exported template item will use the default app URL from Web AppBuilder. If you deploy this app to another web server, change this URL in the item\u2019s details page.",noTitleMessage:"You must provide a title for your template and tags to make your template searchable.",
exportTemplateFailed1:"Failed to export when adding templateItem to portal.",exportTemplateFailed2:"Failed to export when getting templateGroup from portal.",exportTemplateFailed3:"Exported successfully! However, the exported template item has not been shared to the \u201cWeb App Templates\u201d group. To use the template, you need to manually share it to the group.",exportTemplateFailed4:"Exported successfully! However, failed to share the item to templateGroup.",exportTemplateFailed5:"Failed to export when getting portal user.",
exportTemplateFailed31:"Exported successfully! However, it seems that you don\u2019t have permission to share the template",exportTemplateFailed32:"to the template group specified in your organization. You need to manually add it to the group once it is accessible.",descriptionTemplateUrl1:"Click",descriptionTemplateUrl2:"here",descriptionTemplateUrl21:"item",descriptionTemplateUrl3:"to see details of the exported template.",exportSuccessful:"Exported as web app template successfully.",exportMessageTitle:"Export as web app template",
templateDefaultSnippet:"A configurable application template generated by Web AppBuilder.",exportSuccessfulUpdate:"Update web app template successfully.",exportMessageTitleUpdate:"Update web app template",exportTemplateFailed6:"Failed to update when getting portal user.",exportTemplateFailed7:"Failed to update template item.",noTitleMessageForWAB:"You must provide a title for your template.",templateTitleForWAB:"You are going to export current app as a web app template.",exportSuccessfulForWab:"Exported as web app template successfully.",
exportPopupTitleForWab:"Export as web app template",appProperties:"App properties",exportStr:"Export",templateConfigUIPreview:"Template Config UI Preview",templateLabel:"Template:",userLevelTip:"Web AppBuilder Developer Edition requires a level 2 ArcGIS account to work. Please login with an account that has level 2 privileges.",sharedTheme:"Organization shared",custom:"Custom...",setLogo:"Set logo",setRefreshInterval:"Set refresh interval",refreshTip:"A refresh interval keeps your layers in sync with the latest data. \nThis setting is only applicable to the layers whose refresh intervals are activated.",
refreshInterval:"Refresh interval",defaultRefreshTip:"Honor each layer\u2019s interval",singleRefreshTip:"Use a single interval for all non-static layers",seconds:"Seconds",minutes:"Minutes",700001:"Create app error.",700002:"The app exists already. Please choose another name.",700003:"Save icon failed.",700004:"Save app thumbnail failed.",700005:"Invalid App.",700006:"Invalid Zip."},ar:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,et:1,fi:1,fr:1,he:1,hi:1,hr:1,hu:1,it:1,id:1,ja:1,ko:1,lt:1,lv:1,nb:1,nl:1,
pl:1,"pt-br":1,"pt-pt":1,ro:1,ru:1,sl:1,sr:1,sv:1,th:1,tr:1,vi:1,"zh-cn":1,"zh-hk":1,"zh-tw":1});