define({
  "viz_settings": "Visualisointiasetukset",
  "viz_type": "Visualisointityyppi",
  "max_height": "Symbolin enimmäiskorkeus (metreinä)",
  "max_width": "Symbolin enimmäisleveys (metreinä)",
  "interval": "Aikaväli (millisekunteina)",
  "show_percent": "Näytä arvot prosenttiosuutena kaikista arvoista",
  "show_jettrail_end_points": "Näytä loppupisteet",
  "show_percentage_limited": "Tämä on poistettu käytöstä, koska tietueita on yli 400.",
  "cycle_colors": "Vaihda värejä automaattisesti",
  "area_extrusion": "Alueelle tunkeutuminen",
  "bounce": "Ponnahdus",
  "fireball": "Tulipallo",
  "grid_surface": " Ruudukon pinta",
  "jet_trail": "Lentokoneen perävana",
  "point_extrusion": "Pisteen puristus",
  "pulse": "Pulssi",
  "layer_settings": "Karttatason asetukset",
  "viz_layer": "Visualisointikarttataso",
  "display_field": "Näyttökenttä",
  "add_field": "Lisää visualisointikenttä",
  "field": "Kenttä",
  "label": "Tunnusteksti",
  "actions": "Toimet",
  "no_layers": " Valitussa Web-maisemassa ei ole käytettävissä olevia karttatasoja.",
  "viz_not_supported": "Ei tueta valitun karttatason geometriatyypille."
});