define({
  "viz_settings": "Visualiseringsinnstillinger",
  "viz_type": "Visualiseringstype",
  "max_height": "Maks. symbolhøyde (meter)",
  "max_width": "Maks. symbolbredde (meter)",
  "interval": "Intervall (millisekunder)",
  "show_percent": "Vis verdier som prosent av alle verdier",
  "show_jettrail_end_points": "Vis sluttpunkter",
  "show_percentage_limited": "Deaktivert siden antall poster overstiger 400.",
  "cycle_colors": "Endre farger automatisk",
  "area_extrusion": "Områdesprojeksjon",
  "bounce": "Hopp",
  "fireball": "Ildkule",
  "grid_surface": " Rutenettflate",
  "jet_trail": "Kondensstriper",
  "point_extrusion": "Punktprojeksjon",
  "pulse": "Puls",
  "layer_settings": "Laginnstillinger",
  "viz_layer": "Visualiseringslag",
  "display_field": "Visningsfelt",
  "add_field": "Legg til visualiseringsfelt",
  "field": "Felt",
  "label": "Etikett",
  "actions": "Handlinger",
  "no_layers": " Det er ingen tilgjengelige lag i den valgte webscenen.",
  "viz_not_supported": "Støttes ikke for geometritypen for det valgte laget."
});