define({
  "viz_settings": "Visualiseerimise seaded",
  "viz_type": "Visualiseerimise tüüp",
  "max_height": "Sümboli max kõrgus (meetrites)",
  "max_width": "Sümboli max laius (meetrites)",
  "interval": "Intervall (millisekundites)",
  "show_percent": "Kuva väärtused protsendimäärana kõikidest väärtustest",
  "show_jettrail_end_points": "Kuva lõpp-punktid",
  "show_percentage_limited": "See on keelatud, sest kirjete koguarv on suurem kui 400.",
  "cycle_colors": "Muuda automaatselt värve",
  "area_extrusion": "Ala ärajätmine",
  "bounce": "Põrge",
  "fireball": "Tulekera",
  "grid_surface": " Ruudustikuga pind",
  "jet_trail": "Lennukijälg",
  "point_extrusion": "Punkti väljaulatus",
  "pulse": "Impulss",
  "layer_settings": "Kihi seaded",
  "viz_layer": "Visualiseerimise kiht",
  "display_field": "Kuvamise väli",
  "add_field": "Lisa visualiseerimise väli",
  "field": "Väli",
  "label": "Märgis",
  "actions": "Toimingud",
  "no_layers": " Valitud veebistseenis pole saadaval ühtki kihti.",
  "viz_not_supported": "Valitud kihi geomeetria tüüp ei toeta seda."
});