define({
  "viz_settings": "Nastavení vizualizace",
  "viz_type": "Typ vizualizace",
  "max_height": "Maximální výška symbolů (metry)",
  "max_width": "Maximální šířka symbolů (metry)",
  "interval": "Interval (milisekundy)",
  "show_percent": "Zobrazit hodnoty jako procento všech hodnot",
  "show_jettrail_end_points": "Zobrazit koncové body",
  "show_percentage_limited": "Tato funkce je zakázána, protože počet záznamů je vyšší než 400.",
  "cycle_colors": "Automaticky měnit barvy",
  "area_extrusion": "Vytažení plochy",
  "bounce": "Odraz",
  "fireball": "Ohnivá koule",
  "grid_surface": " Povrch mřížky",
  "jet_trail": "Kondenzační stopa",
  "point_extrusion": "Vytažení bodů",
  "pulse": "Pulzování",
  "layer_settings": "Nastavení vrstvy",
  "viz_layer": "Vrstva vizualizace",
  "display_field": "Zobrazované pole",
  "add_field": "Přidat pole vizualizace",
  "field": "Pole",
  "label": "Štítek",
  "actions": "Akce",
  "no_layers": " Ve zvolené webové scéně nejsou k dispozici žádné vrstvy.",
  "viz_not_supported": "Není podporováno pro typ geometrie vybrané vrstvy."
});