define({
  "viz_settings": "إعدادات المرئيات",
  "viz_type": "نوع المرئيات",
  "max_height": "أقصى ارتفاع للرمز (بالمتر)",
  "max_width": "أقصى عرض للرمز (بالمتر)",
  "interval": "فاصل (مللي ثانية)",
  "show_percent": "عرض القيم كنسبة مئوية لكل القيم",
  "show_jettrail_end_points": "إظهار نقاط النهاية",
  "show_percentage_limited": "يكون هذا معطل نظرًا لأن عدد السجلات أكبر من 400.",
  "cycle_colors": "تغيير اللون تلقائيًا",
  "area_extrusion": "إقصاء المنطقة",
  "bounce": "وثب",
  "fireball": "كرة اللهب",
  "grid_surface": " سطح الشبكة",
  "jet_trail": "احصل على نسخة تجريبية",
  "point_extrusion": "إقصاء النقطة",
  "pulse": "نبض",
  "layer_settings": "إعدادات الطبقة",
  "viz_layer": "طبقة المرئيات",
  "display_field": "عرض الحقل",
  "add_field": "إضافة حقل مرئيات",
  "field": "حقل",
  "label": "التسمية",
  "actions": "إجراءات",
  "no_layers": " لا تتوفر طبقات في مشهد الويب المحدد.",
  "viz_not_supported": "غير مدعوم للنوع الهندسي للطبقة المحددة."
});