define({
  "viz_settings": "視覺化設定",
  "viz_type": "視覺化類型",
  "max_height": "最大符號高度 (公尺)",
  "max_width": "最大符號寬度 (公尺)",
  "interval": "間隔 (毫秒)",
  "show_percent": "將值顯示為所有值的百分比",
  "show_jettrail_end_points": "顯示端點",
  "show_percentage_limited": "已停用此動作，因為記錄數目大於 400。",
  "cycle_colors": "自動變更顏色",
  "area_extrusion": "區域拉伸",
  "bounce": "彈跳",
  "fireball": "火球",
  "grid_surface": " 方格曲面",
  "jet_trail": "射流軌跡",
  "point_extrusion": "點拉伸",
  "pulse": "脈衝",
  "layer_settings": "圖層設定",
  "viz_layer": "視覺化圖層",
  "display_field": "顯示欄位",
  "add_field": "新增視覺化欄位",
  "field": "欄位",
  "label": "標籤",
  "actions": "操作",
  "no_layers": " 選擇的 Web 場景中無可用的圖層。",
  "viz_not_supported": "不支援所選圖層的幾何類型。"
});