define({
  "viz_settings": "Paramètres de visualisation",
  "viz_type": "Type de visualisation",
  "max_height": "Hauteur de symbole max. (mètres)",
  "max_width": "Largeur de symbole max. (mètres)",
  "interval": "Intervalle (millisecondes)",
  "show_percent": "Afficher les valeurs sous forme de pourcentage de toutes les valeurs",
  "show_jettrail_end_points": "Afficher les extrémités",
  "show_percentage_limited": "Cette option est désactivée car le nombre d’enregistrements est supérieur à 400.",
  "cycle_colors": "Changer automatiquement les couleurs",
  "area_extrusion": "Extrusion de surface",
  "bounce": "Renvoyer",
  "fireball": "Boule de feu",
  "grid_surface": " Surface de grille",
  "jet_trail": "Trace d'avion",
  "point_extrusion": "Extrusion de points",
  "pulse": "Impulsion",
  "layer_settings": "Paramètres de la couche",
  "viz_layer": "Couche de visualisation",
  "display_field": "Champ d’affichage",
  "add_field": "Ajouter un champ de visualisation",
  "field": "Champ",
  "label": "Etiqueter",
  "actions": "Actions",
  "no_layers": " Aucune couche disponible dans la scène Web sélectionnée.",
  "viz_not_supported": "Non pris en charge pour le type de géométrie de la couche sélectionnée."
});