define({
  "viz_settings": "Configurações de visualização",
  "viz_type": "Tipo de visualização",
  "max_height": "Altura máxima do Símbolo (metros)",
  "max_width": "Largura máxima do símbolo (metros)",
  "interval": "Intervalo (milesegundos)",
  "show_percent": "Mostrar valores como porcentagem de todos os valores",
  "show_jettrail_end_points": "Mostrar pontos finais",
  "show_percentage_limited": "Isto é desativado já que o número de registros é maior que 400.",
  "cycle_colors": "Alterar cores automaticamente",
  "area_extrusion": "Extrusão de área",
  "bounce": "Pular",
  "fireball": "Bola de Fogo",
  "grid_surface": " Superfície de grade",
  "jet_trail": "Trilha de jato",
  "point_extrusion": "Extrusão de ponto",
  "pulse": "Pulso",
  "layer_settings": "Configurações da camada",
  "viz_layer": "Camada de visualização",
  "display_field": "Campo de visualização",
  "add_field": "Adicionar campo de visualização",
  "field": "Campo",
  "label": "Rótulo",
  "actions": "Ações",
  "no_layers": " Nenhuma camada disponível na cena da web selecionada.",
  "viz_not_supported": "Não suportado para tipo de geometria da camada selecionada."
});