// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:builder/plugins/creation-entry/CreateNewAppPage.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"app-select-page" data-dojo-attach-point\x3d"appSelectPage"\x3e\r\n    \x3cdiv class\x3d"switch-btn-box-container"\x3e\r\n      \x3cdiv class\x3d"switch-btn-box"\x3e\r\n        \x3cdiv class\x3d"switch-btn all-app-btn selected" data-dojo-attach-point\x3d"allAppBtn"\r\n             data-dojo-attach-event\x3d"onclick:_onAllAppBtnClick"\x3e ${nls.all}\r\n        \x3c/div\x3e\r\n        \x3cdiv class\x3d"separate"\x3e\x3c/div\x3e\r\n        \x3cdiv class\x3d"switch-btn own-app-btn" data-dojo-attach-point\x3d"ownAppBtn"\r\n             data-dojo-attach-event\x3d"onclick:_onOwnAppBtnClick"\x3e ${nls.myTemplates}\r\n        \x3c/div\x3e\r\n      \x3c/div\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"app-content all-app-content" data-dojo-attach-point\x3d"allAppContent"\x3e\r\n      \x3cdiv class\x3d"app-line" data-dojo-attach-point\x3d"defaultApps"\x3e\x3c/div\x3e\r\n      \x3cdiv class\x3d"app-line" data-dojo-attach-point\x3d"othersApps"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"app-content own-app-content" data-dojo-attach-point\x3d"ownAppContent"\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"app-info-page" data-dojo-attach-point\x3d"appInfoPage"\x3e\r\n    \x3cdiv class\x3d"app-info-table" data-dojo-attach-point\x3d"appInfoTable"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/_base/array dojo/_base/html builder/BasePlugin dojo/dom-style dijit/_WidgetsInTemplateMixin dojo/text!./CreateNewAppPage.html dojo/query dojo/on dojo/dom-class dojo/_base/lang dojo/Evented builder/dijit/EditItemInfo builder/serviceUtils jimu/portalUrlUtils builder/portalUtils jimu/utils".split(" "),function(l,d,b,m,n,p,q,f,r,k,g,t,u,v,w,x,h){return l([m,p,t],{templateString:q,baseClass:"create-app-page",appInfo:null,pluginManager:null,postMixInProperties:function(){this.inherited(arguments)},
postCreate:function(){this.inherited(arguments)},startup:function(){"undefined"===typeof this.isPortalSupport3D&&(this.isPortalSupport3D=!1);this.isPortalSupport3D=!!this.isPortalSupport3D;this.initAppInfoPage();this.createFromAppInfo?(this.selectedApp=this.createFromAppInfo,this._displaySecondPage(),this._hideButton(1)):(this.initAppSelectPage(),this._displayFirstPage())},destroy:function(){this.itemInfoDijit&&(this.itemInfoDijit.destroy(),this.itemInfoDijit=null);this.popup&&(this.popup=null);b.destroy(this.domNode);
this.inherited(arguments)},initAppSelectPage:function(){this._stemappExtensions=this.pluginManager.getExtensions("startup.stemapps");this._stemappExtensions.sort(function(a,c){return a.parameters.index-c.parameters.index});v.getTemplateList(!0).then(g.hitch(this,function(a){var c=this._filterInfosByIsPortalSupport3D(a);d.forEach(c,function(a){!a.id||"HTML_default"!==a.id&&"HTML3D_default"!==a.id?this._createAppNodeAndBindEvent(a,this.othersApps):("HTML_default"===a.id?a.name=this.nls.Default2D:"HTML3D_default"===
a.id&&(a.name=this.nls.Default3D),this._createAppNodeAndBindEvent(a,this.defaultApps))},this);this._selecteApp(f(".app-image-border-div",this.allAppContent)[0]);c=w.getStandardPortalUrl(window.portalUrl);x.getPortal(c).getUser().then(g.hitch(this,function(c){var b=d.filter(a,function(a){return a.isTemplate&&a.creator===c.username}),b=this._filterInfosByIsPortalSupport3D(b);d.forEach(b,function(a){this._createAppNodeAndBindEvent(a,this.ownAppContent)},this)}))}))},_filterInfosByIsPortalSupport3D:function(a){var b=
this.isPortalSupport3D;return d.filter(a,function(a){return!1===b?"HTML3D"!==a.appType:!0})},initAppInfoPage:function(){this.itemInfoDijit=new u({itemInfo:this.appInfo,nls:this.nls});this.itemInfoDijit.placeAt(this.appInfoTable)},_createAppNode:function(a,c,e){this.zIndex=10;c=b.create("div",{"class":"app-node jimu-float-leading",style:e},c);e=b.create("div",{"class":"app-image-border-div",title:h.stripHTML(a.description)},c);b.create("div",{"class":"app-image-div",style:{backgroundImage:"url("+a.thumbnail+
")"}},e);var d;"HTML"===a.appType?d="2D":"HTML3D"===a.appType&&(d="3D");d=b.create("div",{"class":"flag-image flag-image-"+d},e);n.set(d,"z-index",this.zIndex++);b.create("div",{"class":"app-name",innerHTML:h.stripHTML(a.name),title:h.stripHTML(a.name)},c);return e},_createAppNodeAndBindEvent:function(a,b){b=this._createAppNode(a,b);this.own(r(b,"click",g.hitch(this,this._onAppNodeClick,b)));b.appInfo=a;return b},_onAppNodeClick:function(a){var b=f(".app-image-border-div",this.appSelectPage);d.forEach(b,
function(a){this._unselecteApp(a)},this);this._selecteApp(a)},_selecteApp:function(a){this.selectedApp=a.appInfo;k.add(a,"jimu-state-active")},_unselecteApp:function(a){k.remove(a,"jimu-state-active")},_onAllAppBtnClick:function(){var a=f(".app-image-border-div",this.allAppContent)[0];a&&(this._onAppNodeClick(a),this.creationEntryPlugin.createAppPopup.enableButton(0));b.setStyle(this.allAppContent,"display","block");b.setStyle(this.ownAppContent,"display","none");b.addClass(this.allAppBtn,"selected");
b.removeClass(this.ownAppBtn,"selected")},_onOwnAppBtnClick:function(){var a=f(".app-image-border-div",this.ownAppContent)[0];a?(this._onAppNodeClick(a),this.creationEntryPlugin.createAppPopup.enableButton(0)):this.creationEntryPlugin.createAppPopup.disableButton(0);b.setStyle(this.allAppContent,"display","none");b.setStyle(this.ownAppContent,"display","block");b.addClass(this.ownAppBtn,"selected");b.removeClass(this.allAppBtn,"selected")},_onNextClick:function(){this._displaySecondPage();"HTML"===
this.selectedApp.appType?this.itemInfoDijit.imageChooser.setDefaultSelfSrc("/webappbuilder/builder/images/appthumbnail_2d.jpg"):this.itemInfoDijit.imageChooser.setDefaultSelfSrc("/webappbuilder/builder/images/appthumbnail_3d.jpg")},_onBackClick:function(){this._displayFirstPage()},_displayFirstPage:function(){b.setStyle(this.appInfoPage,"display","none");b.setStyle(this.appSelectPage,"display","block");this._displayButtion(0);this._hideButton(1);this._hideButton(2);this.popup&&this.popup.resize()},
_displaySecondPage:function(){b.setStyle(this.appSelectPage,"display","none");b.setStyle(this.appInfoPage,"display","block");this._hideButton(0);this._displayButtion(1);this._displayButtion(2);this.popup&&this.popup.resize();this.itemInfoDijit&&this.itemInfoDijit.focusItemByName("appName")},setPopup:function(a){this.popup=a},_hideButton:function(a){b.setStyle(this.popup.enableButton(a),"display","none")},_displayButtion:function(a){b.setStyle(this.popup.enableButton(a),"display","inline-block")},
_getAppInfoFromDlg:function(){var a=this.itemInfoDijit.getProperties();a.appType=this.selectedApp.appType;a.webmap=this.webmap;a.fromAppId=this.selectedApp.id;a.isPredefined=!1;a.isTemplateApp=this.selectedApp.isTemplate;0===a.icon.indexOf("/webappbuilder/builder/images/")&&(a.icon=null);0===a.thumbnail.indexOf("/webappbuilder/builder/images/")&&(a.thumbnail=null);return a}})});