// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/html dojo/_base/array dojo/Deferred dojo/promise/all dojo/request jimu/utils".split(" "),function(h,g,k,f,l,m,n,e){return h(null,{appConfig:void 0,currentStyleName:void 0,currentLayoutName:void 0,_manifest:void 0,constructor:function(a){this._manifest=a;this.domNodes={}},clear:function(){var a;this.appConfig=null;for(a=0;a<this._manifest.layouts.length;a++)if("appLayout"===this._manifest.layouts[a].name){this._manifest.layouts[a].domNode&&k.destroy(this._manifest.layouts[a].domNode);
this._manifest.layouts.splice(a,1);break}},loadLayouts:function(){var a=new l,b=[],d=f.filter(this._manifest.layouts,function(a){return"appLayout"!==a.name});f.forEach(d,function(a){b.push(n(this._manifest.url+a.uri,{handleAs:"json"}))},this);m(b).then(g.hitch(this,function(b){var c;f.forEach(d,function(a,d){a.layoutConfig=b[d];"default"===a.name?c=a.layoutConfig:(d=a.layoutConfig.layoutDefinition,a.layoutConfig=e.mixinAppConfigPosition(c,a.layoutConfig),a.layoutConfig.layoutDefinition=d);a.layoutConfig.mobileLayout&&
(a.layoutConfig.mobileLayout=e.mixinAppConfigPosition(a.layoutConfig,a.layoutConfig.mobileLayout),delete a.layoutConfig.mobileLayout.mobileLayout)},this);a.resolve()}),function(){a.reject()});return a},_processLayoutConfig:function(a,b){return e.mixinAppConfigPosition(a,b)},setAppConfig:function(a){this.appConfig=a},getName:function(){return this._manifest.name},getVersion:function(){return this._manifest.version},getLabel:function(){return this._manifest.label},getIcon:function(){return this._manifest.icon},
getLayouts:function(){return this._manifest.layouts},getStyles:function(){return this._manifest.styles},getUrl:function(){return this._manifest.url},getCurrentStyle:function(){return this.getStyleByName(this.currentStyleName)},getCurrentLayout:function(){return this.getLayoutByName(this.currentLayoutName)},changeCurrentStyle:function(a){this.currentStyleName=a},changeCurrentLayout:function(a){this.currentLayoutName=a},addLayout:function(a,b,d,c){var e,f=this.getLayouts();for(e=0;e<f.length;e++)if(f[e].name===
a)return null;a={description:"this is current app layout",name:a,label:c,layoutConfig:b,domClass:d};this._manifest.layouts.push(a);return a},getStyleByName:function(a){var b,d=null;for(b=0;b<this._manifest.styles.length;b++)if(this._manifest.styles[b].name===a){d=this._manifest.styles[b];break}return d},getLayoutByName:function(a){var b,d=null;for(b=0;b<this._manifest.layouts.length;b++)if(this._manifest.layouts[b].name===a){d=this._manifest.layouts[b];break}return d},getLayoutByAppConfig:function(a){var b,
d=null;for(b=0;b<this._manifest.layouts.length;b++)if(this.isAppUseLayout(a,this._manifest.layouts[b].layoutConfig)){d=this._manifest.layouts[b];break}return d},isAppUseLayout:function(a,b){a=g.clone(a);b=g.clone(b);a.map||(a.map={});b.map||(b.map=a.map);a.map.position||(a.map.position={left:0,top:0});b.map.position||(b.map.position=a.map.position);if(!e.isEqual(a.layoutDefinition,b.layoutDefinition)||!e.isEqual(a.map.position,b.map.position))return!1;a.widgetOnScreen||(a.widgetOnScreen={});b.widgetOnScreen||
(b.widgetOnScreen={});a.widgetOnScreen.widgets||(a.widgetOnScreen.widgets=[]);b.widgetOnScreen.widgets||(b.widgetOnScreen.widgets=[]);a.widgetOnScreen.groups||(a.widgetOnScreen.groups=[]);b.widgetOnScreen.groups||(b.widgetOnScreen.groups=[]);var d,c;d=a.widgetOnScreen.widgets.length<b.widgetOnScreen.widgets.length?a.widgetOnScreen.widgets.length:b.widgetOnScreen.widgets.length;for(c=0;c<d;c++)if(a.widgetOnScreen.widgets[c].position||(a.widgetOnScreen.widgets[c].position={}),b.widgetOnScreen.widgets[c].position||
(b.widgetOnScreen.widgets[c].position=a.widgetOnScreen.widgets[c].position),b.widgetOnScreen.widgets[c].position.relativeTo||(b.widgetOnScreen.widgets[c].position.relativeTo=a.widgetOnScreen.widgets[c].position.relativeTo),!e.isEqual(a.widgetOnScreen.widgets[c].position,b.widgetOnScreen.widgets[c].position))return!1;d=a.widgetOnScreen.groups.length<b.widgetOnScreen.groups.length?a.widgetOnScreen.groups.length:b.widgetOnScreen.groups.length;for(c=0;c<d;c++)if(a.widgetOnScreen.groups[c].panel||(a.widgetOnScreen.groups[c].panel=
{}),b.widgetOnScreen.groups[c].panel||(b.widgetOnScreen.groups[c].panel=a.widgetOnScreen.groups[c].panel),a.widgetOnScreen.groups[c].panel.position||(a.widgetOnScreen.groups[c].panel.position={}),b.widgetOnScreen.groups[c].panel.position||(b.widgetOnScreen.groups[c].panel.position=a.widgetOnScreen.groups[c].panel.position),b.widgetOnScreen.groups[c].panel.position.relativeTo||(b.widgetOnScreen.groups[c].panel.position.relativeTo=a.widgetOnScreen.groups[c].panel.position.relativeTo),!e.isEqual(a.widgetOnScreen.groups[c].panel.position,
b.widgetOnScreen.groups[c].panel.position))return!1;return!0},getLayoutFromConfig:function(a){var b={};a=g.clone(a);a.widgetOnScreen&&(b.widgetOnScreen={},a.widgetOnScreen.widgets&&(b.widgetOnScreen.widgets=[],f.forEach(a.widgetOnScreen.widgets,function(a,c){b.widgetOnScreen.widgets[c]={position:a.position?a.position:{left:0,top:0}}})),a.widgetOnScreen.groups&&(b.widgetOnScreen.groups=[],f.forEach(a.widgetOnScreen.groups,function(a,c){b.widgetOnScreen.groups[c]={position:a.position?a.position:{left:0,
top:0}}})));a.map&&(b.map={position:a.map.position});return b}})});