// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/Evented dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dojo/_base/lang dojo/_base/html dojo/on dojo/_base/Color builder/dijit/SharedThemeChooserPopup jimu/dijit/ColorPickerPopup jimu/utils".split(" "),function(f,g,h,k,c,e,d,l,m,n,p){return g([h,k,f],{baseClass:"jimu-theme-color-chooser",declaredClass:"jimu.dijit.ThemeColorChooser",templateString:'\x3cdiv class\x3d"jimu-color-picker"\x3e\x3c/div\x3e',color:null,showLabel:!1,recordUID:"",isPortalSupport:!1,postCreate:function(){this.inherited(arguments)},
startup:function(){this._createTooltipDialog();this.own(d(this.domNode,"click",c.hitch(this,function(a){a.stopPropagation();a.preventDefault();this.emit("clickContainer",this.getColor())})));this.own(d(this.domNode,"mouseenter",c.hitch(this,function(){this.popup.showPopup()})));this.own(d(this.domNode,"mouseleave",c.hitch(this,function(){this.popup.hidePopup()})))},destroy:function(){this.colorPickerPopup.picker.destroy();this.popup.destroy();this.inherited(arguments)},showSharedThemeColor:function(a){this.popup.setChecked(this.popup.ACTION.SHARED);
this.emitSharedThemeChangedEvent(!0,a)},showCustomColor:function(a){a&&(a.stopPropagation(),a.preventDefault());this.popup.hidePopup();this.colorPickerPopup.showTooltipDialog();this.colorPickerPopup.initUI()},emitSharedThemeChangedEvent:function(a,b){!1!==b&&(this._useHeader=a,this.emit("sharedThemeChanged",this.getColor(),{useHeader:this._useHeader}));this.popup.hideTooltipDialog()},_createTooltipDialog:function(){this.popup=new m({isPortalSupport:this.isPortalSupport,placeAt:this.getParent(),around:this.domNode});
this.own(d(this.popup,"btnClick",c.hitch(this,function(a,b){a===this.popup.ACTION.SHARED?this.showSharedThemeColor():a===this.popup.ACTION.CUSTOM&&this.showCustomColor(b)})));this.own(d(this.popup,"showPopup",c.hitch(this,function(){this._isNoChooseState()?this.popup.setChecked("clean"):this.popup.setChecked(this._useHeader?this.popup.ACTION.SHARED:this.popup.ACTION.CUSTOM)})));this.colorPickerPopup=new n({showColorPickerOK:!0,showLabel:!1,recordUID:this.recordUID,around:this.domNode});this.colorPickerPopup.placeAt(this.getParent());
this.colorPickerPopup.startup();this.own(d(this.colorPickerPopup,"change",c.hitch(this,function(a){this.setColor(a);this.emitSharedThemeChangedEvent(!1);this.popup.setChecked(this.popup.ACTION.CUSTOM)})))},setSharedThemeConfig:function(a){a&&"undefined"!==typeof a.useHeader&&(this._useHeader=a.useHeader,this.popup.setIsPortalSupport(a.isPortalSupport),this._isNoChooseState()||!0===a.useHeader&&this.showSharedThemeColor(!1))},_isNoChooseState:function(){return!1===this._useHeader&&!0===this._isNoChecked?
!0:!1},setNoChecked:function(a){this._isNoChecked=!0===a?!0:!1},setColor:function(a){if(a instanceof l){null===this.color&&!0===this.showLabel&&this._changeLabel(a);var b=a.toHex();this.color=a;this.colorPickerPopup&&(e.setStyle(this.colorPickerPopup.domNode,"backgroundColor",b),this.colorPickerPopup.picker.refreshRecords(),this.colorPickerPopup.picker.setColor(b,!1,!0));this.showLabel&&this._changeLabel(this.color);e.setStyle(this.domNode,"backgroundColor",b)}},getColor:function(){return this.color},
_changeLabel:function(a){e.empty(this.domNode);e.create("span",{innerHTML:a.toHex(),className:"color-label",style:{color:p.invertColor(a.toHex())}},this.domNode)},onChange:function(a){a&&this.showLabel&&this._changeLabel(a)},changeColor:function(){this.colorPickerPopup&&this.colorPickerPopup.picker.changeColor();this.showLabel&&this._changeLabel(this.color)},setTitle:function(a){this.domNode.title=a}})});