define({
  "viz_settings": "可视化设置",
  "viz_type": "可视化类型",
  "max_height": "最大符号高度(米)",
  "max_width": "最大符号宽度(米)",
  "interval": "间隔(毫秒)",
  "show_percent": "以全部值的百分比形式显示值",
  "show_jettrail_end_points": "显示端点",
  "show_percentage_limited": "由于记录数多于 400，因此此配置禁用。",
  "cycle_colors": "自动更改颜色",
  "area_extrusion": "面积拉伸",
  "bounce": "跳跃式",
  "fireball": "火球",
  "grid_surface": " 网格表面",
  "jet_trail": "喷气轨迹",
  "point_extrusion": "点拉伸",
  "pulse": "脉冲",
  "layer_settings": "图层设置",
  "viz_layer": "可视化图层",
  "display_field": "显示字段",
  "add_field": "添加可视化字段",
  "field": "字段",
  "label": "标注",
  "actions": "操作",
  "no_layers": " 所选 web 场景中无可用图层。",
  "viz_not_supported": "不支持所选图层的几何类型。"
});